---@class NETWORK_COLOUR
NETWORK_COLOUR = {
	DEFAULT_COLOUR = 0,
	BLUE_COLOUR = 1,
	RED_COLOUR = 2,
	GREEN_COLOUR = 3,
	YELLOW_COLOUR = 4,
	TURQUOISE_COLOUR = 5,
	PURPLE_COLOUR = 6,
	WHITE_COLOUR = 7,
	ORANGE_COLOUR = 8,
}

---@class ACHIEVEMENT_IDS
ACHIEVEMENT_IDS = {
	VIRALKILLME = 50,
	MPCOOPWINALL = 49,
	MPSTARRATING = 48,
	MPRACEWINALL = 47,
	MPCOMPWINALL = 46,
	MPTEAMWINALL = 45,
	MPCOOPWIN1 = 44,
	MPRACEWIN1 = 43,
	MPCOMPWIN1 = 42,
	MPTEAMWIN1 = 41,
	GAMECOMPLETION100 = 40,
	STREETLIGHTSDOWN = 39,
	STORYDONE = 38,
	KEYMISSION4 = 37,
	METRANDOM = 36,
	FRIENDSLIKEYOU = 35,
	KEYMISSION3 = 34,
	SABOMBCAR = 33,
	UNDERALLBRIDGES = 32,
	HIDDENPACKAGES = 31,
	ASSASSIN = 30,
	USJDONE = 29,
	SMSTHEFTDONE = 28,
	OPENEDALDERNEY = 27,
	KEYMISSION2 = 26,
	HALFMILLION = 25,
	SAHELI = 24,
	DATING = 23,
	ALLHELITOURTAKEN = 22,
	TAXIPASSANGER = 21,
	KEYMISSION0 = 20,
	VIGILDONE = 19,
	WANTEDDONE = 18,
	IMPORTDONE = 17,
	KEYMISSION1 = 16,
	WANTEDLEVEL6STARSURVIVAL = 15,
	CHAINREACTION = 14,
	SAGUNCAR = 13,
	DRUGDONE = 12,
	LOSERATING = 11,
	CARROLLS = 10,
	SATAXI = 9,
	TURKEY = 8,
	BIKEWHEELIE = 7,
	STREETRACE = 6,
	MELEECOUNTER = 5,
	QUBBEAT = 4,
	POOLWIN = 3,
	SCOREDARTGAME = 2,
	THETOUR = 1,
}

--- SET_PLAYER_CONTROL_FLAGS - These are the flags passed into SET_PLAYER_CONTROL
--- NB: These values must match those in PlayerInfo.h, even though not all are exposed to script.
---@class SET_PLAYER_CONTROL_FLAGS
SET_PLAYER_CONTROL_FLAGS = {
	SPC_NONE = 0, -- No flags set
	SPC_AMBIENT_SCRIPT = 2, -- whether this was called by an ambient script
	SPC_CLEAR_TASKS = 4, -- also clears the player's taks
	SPC_REMOVE_FIRES = 8, -- removes fires in the vicinity of the player
	SPC_REMOVE_EXPLOSIONS = 16, -- removes explosions in the vicinity of the player
	SPC_REMOVE_PROJECTILES = 32, -- removes all projectiles
	SPC_DEACTIVATE_GADGETS = 64, -- deactivates all the player's gadgets
	SPC_REENABLE_CONTROL_ON_DEATH = 128, -- re-enables the player's controls if they die whilst not under control
	SPC_LEAVE_CAMERA_CONTROL_ON = 256, -- Leaves the camera control on when disabling player control (Off by default if removing player control, turned back on when resuming control)
	SPC_ALLOW_PLAYER_DAMAGE = 512, -- Allow the player to be damaged even if his control is turned off.
	SPC_DONT_STOP_OTHER_CARS_AROUND_PLAYER = 1024, -- Tells nearby vehicles to stop moving or get out of the way
	SPC_PREVENT_EVERYBODY_BACKOFF = 2048, -- Prevent everybody from backing off when player controls are disabled
	SPC_ALLOW_PAD_SHAKE = 4096, -- Allows pad to rumble
}

---@class ASSISTED_MOVEMENT_FLAGS
ASSISTED_MOVEMENT_FLAGS = {
	ASS_REDUCE_SPEED_FOR_CORNERS = 1, -- these nodes should be slowed down for if necessary
	ASS_IS_UNDERWATER = 2, -- this node is underwater (modifies its behaviour)
}

--- Have to keep in sync with the enum list in crime.h, wanted.meta and parcodegen in wanted.cpp
---@class CRIME_TYPE
CRIME_TYPE = {
	CRIME_NONE = 0,
	CRIME_POSSESSION_GUN = 1,
	CRIME_RUN_REDLIGHT = 2,
	CRIME_RECKLESS_DRIVING = 3,
	CRIME_SPEEDING = 4,
	CRIME_DRIVE_AGAINST_TRAFFIC = 5,
	CRIME_RIDING_BIKE_WITHOUT_HELMET = 6,
	CRIME_LAST_MINOR_CRIME = CRIME_RIDING_BIKE_WITHOUT_HELMET, -- Minor crimes will not automatically make the wanted level go up but it will start a parole instead. If the player does anything wrong doing the parole period he will get a wanted level.
	CRIME_STEAL_VEHICLE = 8,
	CRIME_STEAL_CAR = 9,
	CRIME_LAST_ONE_NO_REFOCUS = CRIME_STEAL_CAR, -- Some crimes will not refocus the search area.
	CRIME_BLOCK_POLICE_CAR = 11,
	CRIME_STAND_ON_POLICE_CAR = 12,
	CRIME_HIT_PED = 13,
	CRIME_HIT_COP = 14,
	CRIME_SHOOT_PED = 15,
	CRIME_SHOOT_COP = 16,
	CRIME_RUNOVER_PED = 17,
	CRIME_RUNOVER_COP = 18,
	CRIME_DESTROY_HELI = 19,
	CRIME_PED_SET_ON_FIRE = 20,
	CRIME_COP_SET_ON_FIRE = 21,
	CRIME_CAR_SET_ON_FIRE = 22,
	CRIME_DESTROY_PLANE = 23,
	CRIME_CAUSE_EXPLOSION = 24,
	CRIME_STAB_PED = 25,
	CRIME_STAB_COP = 26,
	CRIME_DESTROY_VEHICLE = 27,
	CRIME_DAMAGE_TO_PROPERTY = 28,
	CRIME_TARGET_COP = 29,
	CRIME_FIREARM_DISCHARGE = 30,
	CRIME_RESIST_ARREST = 31,
	CRIME_MOLOTOV = 32,
	CRIME_SHOOT_NONLETHAL_PED = 33,
	CRIME_SHOOT_NONLETHAL_COP = 34,
	CRIME_KILL_COP = 35,
	CRIME_SHOOT_AT_COP = 36,
	CRIME_SHOOT_VEHICLE = 37,
	CRIME_TERRORIST_ACTIVITY = 38,
	CRIME_HASSLE = 39,
	CRIME_THROW_GRENADE = 40,
	CRIME_VEHICLE_EXPLOSION = 41,
	CRIME_KILL_PED = 42,
	CRIME_STEALTH_KILL_COP = 43,
	CRIME_SUICIDE = 44,
	CRIME_DISTURBANCE = 45,
	CRIME_CIVILIAN_NEEDS_ASSISTANCE = 46,
	CRIME_STEALTH_KILL_PED = 47,
	CRIME_SHOOT_PED_SUPPRESSED = 48,
	CRIME_JACK_DEAD_PED = 49,
	CRIME_CHAIN_EXPLOSION = 50,
	MAX_CRIMES = 51,
}

--- Match with eWrecklessType in PlayerInfo.h
---@class WRECKLESS_TYPE
WRECKLESS_TYPE = {
	WT_ON_PAVEMENT = 0,
	WT_RAN_RED_LIGHT = 1,
	WT_DROVE_AGAINST_TRAFFIC = 2,
}

---@class TARGETING_MODE_TYPE
TARGETING_MODE_TYPE = {
	TARGETING_OPTION_GTA_TRADITIONAL = 0,
	TARGETING_OPTION_ASSISTED_AIM = 1,
	TARGETING_OPTION_ASSISTED_FREEAIM = 2,
	TARGETING_OPTION_FREEAIM = 3,
}

---@class PLAYER_TARGET_LEVEL
PLAYER_TARGET_LEVEL = {
	PTL_TARGET_EVERYONE = 0,
	PTL_TARGET_STRANGERS = 1,
	PTL_TARGET_ATTACKERS = 2,
}

---@class CLOTH_PACKAGE_TYPE
CLOTH_PACKAGE_TYPE = {
	CLOTH_PACKAGE_DEFAULT = 0,
	CLOTH_PACKAGE_MINIGUN = 1,
	CLOTH_PACKAGE_TOP_SKINNED = 2,
}

--- Match values with eArcadeTeam in game/Peds/PlayerArcadeInformation.h
---@class ARCADE_TEAM
ARCADE_TEAM = {
	eARCADETEAM_NONE = 0,
	eARCADETEAM_COP = 1,
	eARCADETEAM_CROOK = 2,
	eARCADETEAM_NUM_TYPES = 3,
}

--- Match values with eArcadeRole in game/Peds/PlayerArcadeInformation.h
---@class ARCADE_ROLE
ARCADE_ROLE = {
	eARCADEROLE_NONE = 0,
	eARCADEROLE_COP_OFFICER = 1,
	eARCADEROLE_COP_TACTICAL = 2,
	eARCADEROLE_COP_TECH = 3,
	eARCADEROLE_CROOK_SOLDIER = 4,
	eARCADEROLE_CROOK_ENFORCER = 5,
	eARCADEROLE_CROOK_HACKER = 6,
	eARCADEROLE_NUM_TYPES = 7,
}

---@class ARCADE_PASSIVE_ABILITY_TYPE
ARCADE_PASSIVE_ABILITY_TYPE = {
	ARCADE_ABILITY_NONE = -1,
	ARCADE_ABILITY_PARKOUR = 0,
	ARCADE_ABILITY_SNITCH = 1,
	ARCADE_ABILITY_MARATHON_MAN = 2,
	ARCADE_ABILITY_SECOND_WIND = 3,
	ARCADE_ABILITY_HACK_THE_SYSTEM = 4,
	ARCADE_ABILITY_FREIGHT_TRAIN = 5,
	ARCADE_ABILITY_NUM_TYPES = 6,
}

---@class ARCADE_SPECIAL_ABILITY_TYPE
ARCADE_SPECIAL_ABILITY_TYPE = {
	ARCADE_SPECIAL_ABILITY_NONE = -1,
	ARCADE_SPECIAL_ABILITY_ENRAGED = 0,
	ARCADE_SPECIAL_ABILITY_GHOST = 1,
	ARCADE_SPECIAL_ABILITY_SPRINT_SPEED_BOOST = 2,
	ARCADE_SPECIAL_ABILITY_SPIKE_MINE = 3,
	ARCADE_SPECIAL_ABILITY_FULL_THROTTLE = 4,
	ARCADE_SPECIAL_ABILITY_BACKUP = 5,
	ARCADE_SPECIAL_ABILITY_NUM_TYPES = 6,
}

---@class ARCADE_VEHICLE_ABILITY_TYPE
ARCADE_VEHICLE_ABILITY_TYPE = {
	ARCADE_VEHICLE_ABILITY_NONE = -1,
	ARCADE_VEHICLE_ABILITY_NITRO = 0,
	ARCADE_VEHICLE_ABILITY_EMP = 1,
	ARCADE_VEHICLE_ABILITY_PUMPED_UP = 2,
	ARCADE_VEHICLE_ABILITY_OIL_SLICK = 3,
	ARCADE_VEHICLE_ABILITY_KINETIC_RAM = 4,
	ARCADE_VEHICLE_ABILITY_NUM_TYPES = 5,
}

---@class SPECIAL_ABILITY_TYPE
SPECIAL_ABILITY_TYPE = {
	SAT_INVALID = -1,
	SAT_CAR_SLOWDOWN = 0,
	SAT_RAGE = 1,
	SAT_BULLET_TIME = 2,
	SAT_SNAPSHOT = 3,
	SAT_INSULT = 4,
	SAT_ARCADE_ENRAGED = 5,
	SAT_ARCADE_GHOST = 6,
	SAT_ARCADE_SPRINT_SPEED_BOOST = 7,
	SAT_ARCADE_NITRO_COP = 8,
	SAT_ARCADE_NITRO_CROOK = 9,
	SAT_ARCADE_EMP = 10,
	SAT_ARCADE_SPIKE_MINE = 11,
	SAT_ARCADE_FULL_THROTTLE = 12,
	SAT_ARCADE_PUMPED_UP = 13,
	SAT_ARCADE_BACKUP = 14,
	SAT_ARCADE_OIL_SLICK = 15,
	SAT_ARCADE_KINETIC_RAM = 16,
}

--- INFO: Player Incapacitation Query States
---@class INCAPACITATION_STATE
INCAPACITATION_STATE = {
	INCAPACITATION_STATE_INVALID = -1, -- Ped is not in a valid Incapacitation state
	INCAPACITATION_STATE_FALLING = 0,
	INCAPACITATION_STATE_INCAPACITATED = 1,
	INCAPACITATION_STATE_ESCAPING = 2,
	INCAPACITATION_STATE_ARRESTED = 3,
}

