--- Sync with MarkerImportance
---@class REPLAY_IMPORTANCE
REPLAY_IMPORTANCE = {
	REPLAY_IMPORTANCE_LOWEST = 0,
	REPLAY_IMPORTANCE_LOW = 1,
	REPLAY_IMPORTANCE_NORMAL = 2,
	REPLAY_IMPORTANCE_HIGH = 3,
	REPLAY_IMPORTANCE_HIGHEST = 4,
}

---@class GREATEST_MOMENT
GREATEST_MOMENT = {
	FIVE_START_CRIMINAL = 0,
	CHAIN_REACTION = 1,
	BIRD_DOWN = 2,
	SCOPED = 3,
	TOP_GUN = 4,
	AIRTIME = 5,
	UNTOUCHABLE = 6,
	WHEELIE_RIDER = 7,
	BUCKLE_UP = 8,
	ROLLED_OVER = 9,
	DIZZYING_LAWS = 10,
	YANK_THE_CORD = 11,
	ANIMAUL = 12,
	FULLY_MODDED = 13,
	GLORY_HOLE = 14,
}

--- This is reproduced for code in ReplayControl.h (be sure to stay in sync)
---@class REPLAY_START_PARAM
REPLAY_START_PARAM = {
	REPLAY_START_PARAM_HIGHLIGHT = 0,
	REPLAY_START_PARAM_DIRECTOR = 1,
}

