---@class VEHICLE_MISSION
VEHICLE_MISSION = {
	MISSION_NONE = 0, -- 0
	MISSION_CRUISE = 1, -- 1
	MISSION_RAM = 2, -- 2
	MISSION_BLOCK = 3, -- 3
	MISSION_GOTO = 4, -- 4
	MISSION_STOP = 5, -- 5
	MISSION_ATTACK = 6, -- 6
	MISSION_FOLLOW = 7, -- 7
	MISSION_FLEE = 8, -- 8
	MISSION_CIRCLE = 9, -- 9
	MISSION_ESCORT_LEFT = 10, -- 10
	MISSION_ESCORT_RIGHT = 11, -- 11
	MISSION_ESCORT_REAR = 12, -- 12
	MISSION_ESCORT_FRONT = 13, -- 13
	MISSION_GOTO_RACING = 14, -- 14
	MISSION_FOLLOW_RECORDING = 15, -- 15
	MISSION_POLICE_BEHAVIOUR = 16, -- 16
	MISSION_PARK_PERPENDICULAR = 17, -- 17
	MISSION_PARK_PARALLEL = 18, -- 18
	MISSION_LAND = 19, -- 19
	MISSION_LAND_AND_WAIT = 20, -- 20
	MISSION_CRASH = 21, -- 21
	MISSION_PULL_OVER = 22, -- 22
	MISSION_PROTECT = 23, -- 23
}

---@class LOCK_STATE
LOCK_STATE = {
	VEHICLELOCK_NONE = 0,
	VEHICLELOCK_UNLOCKED = 1, -- 1
	VEHICLELOCK_LOCKED = 2, -- 2
	VEHICLELOCK_LOCKOUT_PLAYER_ONLY = 3, -- 3
	VEHICLELOCK_LOCKED_PLAYER_INSIDE = 4, -- 4
	VEHICLELOCK_LOCKED_INITIALLY = 5, -- 5
	VEHICLELOCK_FORCE_SHUT_DOORS = 6, -- 6
	VEHICLELOCK_LOCKED_BUT_CAN_BE_DAMAGED = 7, -- 7
	VEHICLELOCK_LOCKED_BUT_BOOT_UNLOCKED = 8, -- 8
	VEHICLELOCK_LOCKED_NO_PASSENGERS = 9, -- 9
	VEHICLELOCK_CANNOT_ENTER = 10, -- 10
}

---@class GARAGE_TYPE
GARAGE_TYPE = {
	GARAGE_NONE = 0, -- 0
	GARAGE_MISSION = 1, -- 1
	GARAGE_RESPRAY = 2, -- 2
	GARAGE_FOR_SCRIPT_TO_OPEN_AND_CLOSE = 3, -- 3
	GARAGE_AMBIENT_PARKING = 4, -- 4
}

---@class VEHICLE_STATUS
VEHICLE_STATUS = {
	STATUS_PLAYER = 0,
	STATUS_PLAYER_PLAYBACKFROMBUFFER = 1,
	STATUS_SIMPLE = 2,
	STATUS_PHYSICS = 3,
	STATUS_ABANDONED = 4,
	STATUS_WRECKED = 5,
	STATUS_TRAIN_MOVING = 6,
	STATUS_TRAIN_NOT_MOVING = 7,
	STATUS_PLAYER_REMOTE = 8,
	STATUS_PLAYER_DISABLED = 9,
	STATUS_TRAILER = 10,
	STATUS_SIMPLE_TRAILER = 11,
	STATUS_GHOST = 12,
	STATUS_NETWORK = 13,
}

---@class SC_WHEEL_LIST
SC_WHEEL_LIST = {
	SC_WHEEL_CAR_FRONT_LEFT = 0,
	SC_WHEEL_CAR_FRONT_RIGHT = 1,
	SC_WHEEL_CAR_MID_LEFT = 2,
	SC_WHEEL_CAR_MID_RIGHT = 3,
	SC_WHEEL_CAR_REAR_LEFT = 4,
	SC_WHEEL_CAR_REAR_RIGHT = 5,
	SC_WHEEL_BIKE_FRONT = 6,
	SC_WHEEL_BIKE_REAR = 7,
	SC_MAX_WHEELS = 8,
}

---@class SC_DOOR_LIST
SC_DOOR_LIST = {
	SC_DOOR_INVALID = -1,
	SC_DOOR_FRONT_LEFT = 0,
	SC_DOOR_FRONT_RIGHT = 1,
	SC_DOOR_REAR_LEFT = 2,
	SC_DOOR_REAR_RIGHT = 3,
	SC_DOOR_BONNET = 4,
	SC_DOOR_BOOT = 5,
	SC_MAX_DOORS = 6,
}

---@class SC_WINDOW_LIST
SC_WINDOW_LIST = {
	SC_WINDOW_FRONT_LEFT = 0,
	SC_WINDOW_FRONT_RIGHT = 1,
	SC_WINDOW_REAR_LEFT = 2,
	SC_WINDOW_REAR_RIGHT = 3,
	SC_WINDOW_MIDDLE_LEFT = 4,
	SC_WINDOW_MIDDLE_RIGHT = 5,
	SC_WINDSCREEN_FRONT = 6,
	SC_WINDSCREEN_REAR = 7,
}

---@class VEHICLE_LIGHT_SETTING
VEHICLE_LIGHT_SETTING = {
	NO_VEHICLE_LIGHT_OVERRIDE = 0,
	FORCE_VEHICLE_LIGHTS_OFF = 1, -- 1
	FORCE_VEHICLE_LIGHTS_ON = 2, -- 2
	SET_VEHICLE_LIGHTS_ON = 3, -- 3
	SET_VEHICLE_LIGHTS_OFF = 4, -- 4
}

---@class VEHICLE_HEADLIGHT_SHADOW_FLAGS
VEHICLE_HEADLIGHT_SHADOW_FLAGS = {
	NO_HEADLIGHT_SHADOWS = 0,
	HEADLIGHTS_CAST_DYNAMIC_SHADOWS = 1,
	HEADLIGHTS_CAST_STATIC_SHADOWS = 2,
	HEADLIGHTS_CAST_FULL_SHADOWS = 3,
}

---@class CUSTOM_PLATE_DESIGNS
CUSTOM_PLATE_DESIGNS = {
	CARPLATE_DESIGN_SF = 0,
	CARPLATE_DESIGN_VEGAS = 1, -- 1
	CARPLATE_DESIGN_LA = 2, -- 2
	CARPLATEMGR_PLATEDESIGN_NUM = 3, -- 3
}

---@class WINCH_TYPES
WINCH_TYPES = {
	WINCHTYPE_NONE = 0,
	WINCHTYPE_MAGNET = 1, -- 1
	WINCHTYPE_PEOPLEPICKUP = 2, -- 2
	WINCHTYPE_RCHELI = 3, -- 3
}

---@class VEHICLE_LAYOUT_TYPE
VEHICLE_LAYOUT_TYPE = {
	LAYOUT_INVALID = 0,
	LAYOUT_4X4 = GetHashKey("LAYOUT_4X4"),
	LAYOUT_BISON = GetHashKey("LAYOUT_BISON"),
	LAYOUT_LOW = GetHashKey("LAYOUT_LOW"),
	LAYOUT_LOW_BFINJECTION = GetHashKey("LAYOUT_LOW_BFINJECTION"),
	LAYOUT_LOW_CHEETAH = GetHashKey("LAYOUT_LOW_CHEETAH"),
	LAYOUT_LOW_DUNE = GetHashKey("LAYOUT_LOW_DUNE"),
	LAYOUT_LOW_ENTITYXF = GetHashKey("LAYOUT_LOW_ENTITYXF"),
	LAYOUT_LOW_INFERNUS = GetHashKey("LAYOUT_LOW_INFERNUS"),
	LAYOUT_LOW_RESTRICTED = GetHashKey("LAYOUT_LOW_RESTRICTED"),
	LAYOUT_LOW_SENTINEL2 = GetHashKey("LAYOUT_LOW_SENTINEL2"),
	LAYOUT_RANGER = GetHashKey("LAYOUT_RANGER"),
	LAYOUT_RANGER_SWAT = GetHashKey("LAYOUT_RANGER_SWAT"),
	LAYOUT_STANDARD = GetHashKey("LAYOUT_STANDARD"),
	LAYOUT_STD_EXITFIXUP = GetHashKey("LAYOUT_STD_EXITFIXUP"),
	LAYOUT_STD_HIGHWINDOW = GetHashKey("LAYOUT_STD_HIGHWINDOW"),
	LAYOUT_STD_HABANERO = GetHashKey("LAYOUT_STD_HABANERO"),
	LAYOUT_STD_LOWROOF = GetHashKey("LAYOUT_STD_LOWROOF"),
	LAYOUT_STD_RIPLEY = GetHashKey("LAYOUT_STD_RIPLEY"),
	LAYOUT_STD_STRATUM = GetHashKey("LAYOUT_STD_STRATUM"),
	LAYOUT_STD_STRETCH = GetHashKey("LAYOUT_STD_STRETCH"),
	LAYOUT_STD_ZTYPE = GetHashKey("LAYOUT_STD_ZTYPE"),
	LAYOUT_VAN = GetHashKey("LAYOUT_VAN"),
	LAYOUT_VAN_BODHI = GetHashKey("LAYOUT_VAN_BODHI"),
	LAYOUT_VAN_BOXVILLE = GetHashKey("LAYOUT_VAN_BOXVILLE"),
	LAYOUT_VAN_CADDY = GetHashKey("LAYOUT_VAN_CADDY"),
	LAYOUT_VAN_JOURNEY = GetHashKey("LAYOUT_VAN_JOURNEY"),
	LAYOUT_VAN_MULE = GetHashKey("LAYOUT_VAN_MULE"),
	LAYOUT_VAN_POLICE = GetHashKey("LAYOUT_VAN_POLICE"),
	LAYOUT_VAN_PONY = GetHashKey("LAYOUT_VAN_PONY"),
	LAYOUT_VAN_TRASH = GetHashKey("LAYOUT_VAN_TRASH"),
	LAYOUT_4X4_DUBSTA = GetHashKey("LAYOUT_4X4_DUBSTA"),
	LAYOUT_LOW_BLADE = GetHashKey("LAYOUT_LOW_BLADE"),
	LAYOUT_LOW_DUKES2 = GetHashKey("LAYOUT_LOW_DUKES2"),
	LAYOUT_LOW_TURISMOR = GetHashKey("LAYOUT_LOW_TURISMOR"),
	LAYOUT_LOW_FURORE = GetHashKey("LAYOUT_LOW_FURORE"),
	LAYOUT_LOW_OSIRIS = GetHashKey("LAYOUT_LOW_OSIRIS"),
	LAYOUT_LOW_FELTZER3 = GetHashKey("LAYOUT_LOW_FELTZER3"),
	LAYOUT_LOW_VERLIERER = GetHashKey("LAYOUT_LOW_VERLIERER"),
	LAYOUT_STD_BALLER4 = GetHashKey("LAYOUT_STD_BALLER4"),
	LAYOUT_STD_BASIC = GetHashKey("LAYOUT_STD_BASIC"),
	LAYOUT_STD_BLISTA2 = GetHashKey("LAYOUT_STD_BLISTA2"),
	LAYOUT_STD_CHINO = GetHashKey("LAYOUT_STD_CHINO"),
	LAYOUT_STD_HUNTLEY = GetHashKey("LAYOUT_STD_HUNTLEY"),
	LAYOUT_STD_KURUMA = GetHashKey("LAYOUT_STD_KURUMA"),
	LAYOUT_STD_KURUMA2 = GetHashKey("LAYOUT_STD_KURUMA2"),
	LAYOUT_STD_PANTO = GetHashKey("LAYOUT_STD_PANTO"),
	LAYOUT_STD_TECHNICAL = GetHashKey("LAYOUT_STD_TECHNICAL"),
	LAYOUT_STD_WARRENER = GetHashKey("LAYOUT_STD_WARRENER"),
	LAYOUT_VAN_ARMORED = GetHashKey("LAYOUT_VAN_ARMORED"),
	LAYOUT_VAN_ROOSEVELT = GetHashKey("LAYOUT_VAN_ROOSEVELT"),
	LAYOUT_VAN_SLAMVAN = GetHashKey("LAYOUT_VAN_SLAMVAN"),
	LAYOUT_LOW_LOWRIDER = GetHashKey("LAYOUT_LOW_LOWRIDER"),
	LAYOUT_LOW_LOWRIDER_FACTION = GetHashKey("LAYOUT_LOW_LOWRIDER_FACTION"),
	LAYOUT_LOW_LOWRIDER_FACTION3 = GetHashKey("LAYOUT_LOW_LOWRIDER2_FACTION3"),
	LAYOUT_STD_LOWRIDER = GetHashKey("LAYOUT_STD_LOWRIDER"),
	LAYOUT_STD_LOWRIDER_CHINO = GetHashKey("LAYOUT_STD_LOWRIDER_CHINO"),
	LAYOUT_STD_LOWRIDER_SIDEDOOR = GetHashKey("LAYOUT_STD_LOWRIDER_SIDEDOOR"),
	LAYOUT_STD_LOWRIDER_SLAMVAN = GetHashKey("LAYOUT_STD_LOWRIDER_SLAMVAN"),
}

---@class DOOR_DAMAGE
DOOR_DAMAGE = {
	DT_DOOR_INTACT = 0,
	DT_DOOR_SWINGING_FREE = 1, -- 1
	DT_DOOR_BASHED = 2, -- 2
	DT_DOOR_BASHED_AND_SWINGING_FREE = 3, -- 3
	DT_DOOR_MISSING = 4, -- 4
	DT_DOOR_NO_RESET = 5, -- 5
}

---@class DRIVINGMODE
DRIVINGMODE = {
	DF_StopForCars = 1,
	DF_StopForPeds = 2,
	DF_SwerveAroundAllCars = 4,
	DF_SteerAroundStationaryCars = 8,
	DF_SteerAroundPeds = 16,
	DF_SteerAroundObjects = 32,
	DF_DontSteerAroundPlayerPed = 64,
	DF_StopAtLights = 128,
	DF_GoOffRoadWhenAvoiding = 256,
	DF_DriveIntoOncomingTraffic = 512,
	DF_DriveInReverse = 1024,
	DF_UseWanderFallbackInsteadOfStraightLine = 2048,
	DF_AvoidRestrictedAreas = 4096,
	DF_PreventBackgroundPathfinding = 8192,
	DF_AdjustCruiseSpeedBasedOnRoadSpeed = 16384,
	DF_UseShortCutLinks = 262144,
	DF_ChangeLanesAroundObstructions = 524288,
	DF_UseSwitchedOffNodes = 2097152, -- cruise tasks ignore this anyway--only used for goto's
	DF_PreferNavmeshRoute = 4194304, -- if you're going to be primarily driving off road
	DF_PlaneTaxiMode = 8388608,
	DF_ForceStraightLine = 16777216,
	DF_UseStringPullingAtJunctions = 33554432,
	DF_AvoidHighways = 536870912,
	DF_ForceJoinInRoadDirection = 1073741824,
	DRIVINGMODE_STOPFORCARS = 786603, -- DF_StopForCars|DF_StopForPeds|DF_SteerAroundObjects|DF_SteerAroundStationaryCars|DF_StopAtLights|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions,		// Obey lights too
	DRIVINGMODE_STOPFORCARS_STRICT = 262275, -- DF_StopForCars|DF_StopForPeds|DF_StopAtLights|DF_UseShortCutLinks,		// Doesn't deviate an inch.
	DRIVINGMODE_AVOIDCARS = 786469, -- DF_SwerveAroundAllCars|DF_SteerAroundObjects|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions|DF_StopForCars,
	DRIVINGMODE_AVOIDCARS_RECKLESS = 786468, -- DF_SwerveAroundAllCars|DF_SteerAroundObjects|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions,
	DRIVINGMODE_PLOUGHTHROUGH = 262144, -- DF_UseShortCutLinks
	DRIVINGMODE_STOPFORCARS_IGNORELIGHTS = 786475, -- DF_StopForCars|DF_SteerAroundStationaryCars|DF_StopForPeds|DF_SteerAroundObjects|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions
	DRIVINGMODE_AVOIDCARS_OBEYLIGHTS = 786597, -- DF_SwerveAroundAllCars|DF_StopAtLights|DF_SteerAroundObjects|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions|DF_StopForCars
	DRIVINGMODE_AVOIDCARS_STOPFORPEDS_OBEYLIGHTS = 786599, -- DF_SwerveAroundAllCars|DF_StopAtLights|DF_StopForPeds|DF_SteerAroundObjects|DF_UseShortCutLinks|DF_ChangeLanesAroundObstructions|DF_StopForCars,
}

---@class BOATMODE
BOATMODE = {
	BCF_StopAtEnd = 1,
	BCF_StopAtShore = 2,
	BCF_AvoidShore = 4,
	BCF_PreferForward = 8,
	BCF_NeverStop = 16,
	BCF_NeverNavMesh = 32,
	BCF_NeverRoute = 64,
	BCF_ForceBeached = 128,
	BCF_UseWanderRoute = 256,
	BCF_UseFleeRoute = 512,
	BCF_NeverPause = 1024,
	BCF_DEFAULTSETTINGS = 7, -- CF_StopAtEnd | CF_StopAtShore | CF_AvoidShore
	BCF_OPENOCEANSETTINGS = 111, -- CF_StopAtEnd | CF_StopAtShore | CF_AvoidShore | BCF_PreferForward | BCF_NeverNavMesh | BCF_NeverRoute
	BCF_BOATTAXISETTINGS = 1071, -- CF_StopAtEnd | CF_StopAtShore | CF_AvoidShore | BCF_PreferForward | BCF_NeverNavMesh | BCF_NeverPause
}

---@class HELIMODE
HELIMODE = {
	HF_AttainRequestedOrientation = 1,
	HF_DontModifyOrientation = 2,
	HF_DontModifyPitch = 4,
	HF_DontModifyThrottle = 8,
	HF_DontModifyRoll = 16,
	HF_LandOnArrival = 32,
	HF_DontDoAvoidance = 64,
	HF_StartEngineImmediately = 128,
	HF_ForceHeightMapAvoidance = 256,
	HF_DontClampProbesToDestination = 512,
	HF_EnableTimeslicingWhenPossible = 1024,
	HF_CircleOppositeDirection = 2048,
	HF_MaintainHeightAboveTerrain = 4096,
	HF_IgnoreHiddenEntitiesDuringLand = 8192,
	HF_DisableAllHeightMapAvoidance = 16384,
	HF_NONE = 0,
	HF_HEIGHTMAPONLYAVOIDANCE = 320,
}

---@class DRIVINGSTYLE
DRIVINGSTYLE = {
	DRIVINGSTYLE_NORMAL = 0,
	DRIVINGSTYLE_ACCURATE = 0, -- will be removed eventually
	DRIVINGSTYLE_STRAIGHTLINE = 0, -- will be removed eventually
	DRIVINGSTYLE_RACING = 1,
	DRIVINGSTYLE_REVERSING = 2,
}

---@class TEMPACTION
TEMPACTION = {
	TEMPACT_NONE = 0,
	TEMPACT_WAIT = 1,
	TEMPACT_EMPTYTOBEREUSED = 2,
	TEMPACT_REVERSE = 3,
	TEMPACT_HANDBRAKETURNLEFT = 4,
	TEMPACT_HANDBRAKETURNRIGHT = 5,
	TEMPACT_HANDBRAKESTRAIGHT = 6,
	TEMPACT_TURNLEFT = 7,
	TEMPACT_TURNRIGHT = 8,
	TEMPACT_GOFORWARD = 9,
	TEMPACT_SWERVELEFT = 10,
	TEMPACT_SWERVERIGHT = 11,
	TEMPACT_EMPTYTOBEREUSED2 = 12,
	TEMPACT_REVERSE_LEFT = 13,
	TEMPACT_REVERSE_RIGHT = 14,
	TEMPACT_PLANE_FLY_UP = 15,
	TEMPACT_PLANE_FLY_STRAIGHT = 16,
	TEMPACT_PLANE_SHARP_LEFT = 17,
	TEMPACT_PLANE_SHARP_RIGHT = 18,
	TEMPACT_HEADON_COLLISION = 19,
	TEMPACT_SWERVELEFT_STOP = 20,
	TEMPACT_SWERVERIGHT_STOP = 21,
	TEMPACT_REVERSE_STRAIGHT = 22,
	TEMPACT_BOOST_USE_STEERING_ANGLE = 23,
	TEMPACT_BRAKE = 24,
	TEMPACT_HANDBRAKETURNLEFT_INTELLIGENT = 25,
	TEMPACT_HANDBRAKETURNRIGHT_INTELLIGENT = 26,
	TEMPACT_HANDBRAKESTRAIGHT_INTELLIGENT = 27,
	TEMPACT_REVERSE_STRAIGHT_HARD = 28,
	TEMPACT_EMPTYTOBEREUSED3 = 29,
	TEMPACT_BURNOUT = 30,
	TEMPACT_REV_ENGINE = 31,
	TEMPACT_GOFORWARD_HARD = 32,
	TEMPACT_SURFACE_SUBMARINE = 33,
}

---@class PLAYBACKDISPLAYMODE
PLAYBACKDISPLAYMODE = {
	RDM_NONE = 0,
	RDM_WHOLELINE = 1,
	RDM_JUSTINFRONT = 2,
	RDM_JUSTBEHIND = 3,
	RDM_AROUNDVEHICLE = 4,
}

---@class LANDING_GEAR_COMMAND
LANDING_GEAR_COMMAND = {
	LGC_DEPLOY = 0,
	LGC_RETRACT = 1,
	LGC_DEPLOY_INSTANT = 2,
	LGC_RETRACT_INSTANT = 3,
	LGC_BREAK = 4,
}

---@class LANDING_GEAR_STATE
LANDING_GEAR_STATE = {
	LGS_LOCKED_DOWN = 0,
	LGS_RETRACTING = 1,
	LGS_RETRACTING_INSTANT = 2,
	LGS_DEPLOYING = 3,
	LGS_LOCKED_UP = 4,
	LGS_BROKEN = 5,
}

---@class CONVERTIBLE_ROOF_STATE
CONVERTIBLE_ROOF_STATE = {
	CRS_RAISED = 0,
	CRS_LOWERING = 1,
	CRS_LOWERED = 2,
	CRS_RAISING = 3,
	CRS_CLOSING_BOOT = 4,
	CRS_ROOF_STUCK_RAISED = 5,
	CRS_ROOF_STUCK_LOWERED = 6,
}

---@class MOD_TYPE
MOD_TYPE = {
	MOD_SPOILER = 0,
	MOD_BUMPER_F = 1,
	MOD_BUMPER_R = 2,
	MOD_SKIRT = 3,
	MOD_EXHAUST = 4,
	MOD_CHASSIS = 5,
	MOD_GRILL = 6,
	MOD_BONNET = 7,
	MOD_WING_L = 8,
	MOD_WING_R = 9,
	MOD_ROOF = 10,
	MOD_ENGINE = 11,
	MOD_BRAKES = 12,
	MOD_GEARBOX = 13,
	MOD_HORN = 14,
	MOD_SUSPENSION = 15,
	MOD_ARMOUR = 16,
	MOD_TOGGLE_NITROUS = 17,
	MOD_TOGGLE_TURBO = 18,
	MOD_TOGGLE_SUBWOOFER = 19,
	MOD_TOGGLE_TYRE_SMOKE = 20,
	MOD_TOGGLE_HYDRAULICS = 21,
	MOD_TOGGLE_XENON_LIGHTS = 22,
	MOD_WHEELS = 23,
	MOD_REAR_WHEELS = 24,
	MOD_PLTHOLDER = 25,
	MOD_PLTVANITY = 26,
	MOD_INTERIOR1 = 27,
	MOD_INTERIOR2 = 28,
	MOD_INTERIOR3 = 29,
	MOD_INTERIOR4 = 30,
	MOD_INTERIOR5 = 31,
	MOD_SEATS = 32,
	MOD_STEERING = 33,
	MOD_KNOB = 34,
	MOD_PLAQUE = 35,
	MOD_ICE = 36,
	MOD_TRUNK = 37,
	MOD_HYDRO = 38,
	MOD_ENGINEBAY1 = 39,
	MOD_ENGINEBAY2 = 40,
	MOD_ENGINEBAY3 = 41,
	MOD_CHASSIS2 = 42,
	MOD_CHASSIS3 = 43,
	MOD_CHASSIS4 = 44,
	MOD_CHASSIS5 = 45,
	MOD_DOOR_L = 46,
	MOD_DOOR_R = 47,
	MOD_LIVERY = 48,
}

---@class MOD_KIT_TYPE
MOD_KIT_TYPE = {
	MKT_STANDARD = 0,
	MKT_SPORT = 1,
	MKT_SUV = 2,
	MKT_SPECIAL = 3,
}

---@class MOD_CAMERA_POS
MOD_CAMERA_POS = {
	MCP_DEFAULT = 0,
	MCP_FRONT = 1,
	MCP_FRONT_LEFT = 2,
	MCP_FRONT_RIGHT = 3,
	MCP_REAR = 4,
	MCP_REAR_LEFT = 5,
	MCP_REAR_RIGHT = 6,
	MCP_LEFT = 7,
	MCP_RIGHT = 8,
	MCP_TOP = 9,
	MCP_BOTTOM = 10,
}

---@class MOD_WHEEL_TYPE
MOD_WHEEL_TYPE = {
	MWT_INVALID = -1,
	MWT_SPORT = 0,
	MWT_MUSCLE = 1,
	MWT_LOWRIDER = 2,
	MWT_SUV = 3,
	MWT_OFFROAD = 4,
	MWT_TUNER = 5,
	MWT_BIKE = 6,
	MWT_HIEND = 7,
	MWT_SUPERMOD1 = 8,
	MWT_SUPERMOD2 = 9,
	MWT_SUPERMOD3 = 10,
	MWT_SUPERMOD4 = 11,
	MWT_SUPERMOD5 = 12,
}

---@class MOD_COLOR_TYPE
MOD_COLOR_TYPE = {
	MCT_METALLIC = 0,
	MCT_CLASSIC = 1,
	MCT_PEARLESCENT = 2,
	MCT_MATTE = 3,
	MCT_METALS = 4,
	MCT_CHROME = 5,
	MCT_CHAMELEON = 6,
	MCT_NONE = 7, -- if this is set, the vehicle doesn't use mod colors, it uses the regular color system
}

---@class VEHICLE_PLATE_TYPE
VEHICLE_PLATE_TYPE = {
	VPT_FRONT_AND_BACK_PLATES = 0,
	VPT_FRONT_PLATES = 1,
	VPT_BACK_PLATES = 2,
	VPT_NONE = 3,
}

--- Keep in sync with VehicleResourceFlags in VehicleScriptResource.h
---@class VEHICLE_RESOURCE_FLAGS
VEHICLE_RESOURCE_FLAGS = {
	VRF_REQUEST_SEAT_ANIMS = 1,
	VRF_REQUEST_ENTRY_ANIMS = 2,
	VRF_REQUEST_EXIT_TO_AIM_ANIMS = 4,
	VRF_REQUEST_ALTERNATE_ENTRY_ANIMS = 8,
	VRF_REQUEST_BASIC_ANIMS = 3, -- VRF_REQUEST_SEAT_ANIMS|VRF_REQUEST_ENTRY_ANIMS
	VRF_REQUEST_ALL_ANIMS = 15, -- VRF_REQUEST_SEAT_ANIMS|VRF_REQUEST_ENTRY_ANIMS|VRF_REQUEST_EXIT_TO_AIM_ANIMS|VRF_REQUEST_ALTERNATE_ENTRY_ANIMS
}

---@class VEHICLE_CLASS
VEHICLE_CLASS = {
	VC_COMPACT = 0,
	VC_SEDAN = 1,
	VC_SUV = 2,
	VC_COUPE = 3,
	VC_MUSCLE = 4,
	VC_SPORT_CLASSIC = 5,
	VC_SPORT = 6,
	VC_SUPER = 7,
	VC_MOTORCYCLE = 8,
	VC_OFF_ROAD = 9,
	VC_INDUSTRIAL = 10,
	VC_UTILITY = 11,
	VC_VAN = 12,
	VC_CYCLE = 13,
	VC_BOAT = 14,
	VC_HELICOPTER = 15,
	VC_PLANE = 16,
	VC_SERVICE = 17,
	VC_EMERGENCY = 18,
	VC_MILITARY = 19,
	VC_COMMERCIAL = 20,
	VC_RAIL = 21,
	VC_OPEN_WHEEL = 22,
}

---@class PICKUP_GADGET_TYPE
PICKUP_GADGET_TYPE = {
	PICKUP_HOOK = 0,
	PICKUP_MAGNET = 1,
}

---@class PLANE_DAMAGE_SECTION
PLANE_DAMAGE_SECTION = {
	WING_L = 0,
	WING_R = 1,
	TAIL = 2,
	ENGINE_L = 3,
	ENGINE_R = 4,
	ELEVATOR_L = 5,
	ELEVATOR_R = 6,
	AILERON_L = 7,
	AILERON_R = 8,
	RUDDER = 9,
	RUDDER_2 = 10,
	AIRBRAKE_L = 11,
	AIRBRAKE_R = 12,
}

---@class LANDING_GEAR_DAMAGE_SECTION
LANDING_GEAR_DAMAGE_SECTION = {
	GEAR_F = 0,
	GEAR_RL = 1,
	GEAR_LM1 = 2,
	GEAR_RM = 3,
	GEAR_RM1 = 4,
	GEAR_RR = 5,
}

--- Behaviour flags for when releasing trains back to ambient population
--- Keep in sync with ReleaseTrainFlags enum in CTrain (train.h)
---@class RELEASE_TRAIN_FLAGS
RELEASE_TRAIN_FLAGS = {
	RTF_DEFAULT = 0,
	RTF_KEEP_OLD_SPEED = 1, -- Upon release maintain the speed previously assigned by script, rather than taking it from the track
}

--- Keep in sync with eHomingLockOnState enum in CEntity (Entity.h)
---@class HOMING_LOCKON_STATE
HOMING_LOCKON_STATE = {
	HLOS_NONE = 0,
	HLOS_ACQUIRING = 1,
	HLOS_ACQUIRED = 2,
}

---@class eVehStuckTypes
eVehStuckTypes = {
	VEH_STUCK_ON_ROOF = 0,
	VEH_STUCK_ON_SIDE = 1,
	VEH_STUCK_HUNG_UP = 2,
	VEH_STUCK_JAMMED = 3,
	VEH_STUCK_RESET_ALL = 4,
}

---@class VEHICLE_RECORDING_PLAYBACK_FLAGS
VEHICLE_RECORDING_PLAYBACK_FLAGS = {
	SWITCH_ON_PLAYER_VEHICLE_IMPACT = 1,
	SWITCH_ON_ANY_VEHICLE_IMPACT = 2,
	TURN_ON_ENGINE_INSTANTLY = 4, -- Starts the engine instantly at the start of the car recording.
	TURN_ON_ENGINE_INCLUDING_START = 8, -- Starts the engine including the engine start audio.
	CONTINUE_RECORDING_IF_CAR_DESTROYED = 16, -- Keeps the recording playing if the car dies
}

---@class HANDLING_INFOS
HANDLING_INFOS = {
	HANDLING_SPORTS_CAR = -1532864817,
	HANDLING_AVERAGE = -1103972294,
	HANDLING_CRAP = -2056575896,
	HANDLING_TRUCK = 1115750597,
}

--- Enum for each of the car's potenital neon lights
---@class NEON_ID
NEON_ID = {
	NEON_LEFT = 0,
	NEON_RIGHT = 1,
	NEON_FRONT = 2,
	NEON_BACK = 3,
}

---@class WHEEL_HYDRAULIC_SCRIPT_STATE
WHEEL_HYDRAULIC_SCRIPT_STATE = {
	HS_WHEEL_FREE = 0,
	HS_WHEEL_LOCKED = 1,
	HS_WHEEL_BOUNCE = 2,
	HS_ALL_FREE = 3,
	HS_ALL_LOCK_UP = 4,
	HS_ALL_LOCK_DOWN = 5,
	HS_ALL_BOUNCE = 6,
}

