--- ~>								 Rope Types									<~
---@class PHYSICS_ROPE_TYPE
PHYSICS_ROPE_TYPE = {
	PHYSICS_ROPE_INVALID = -1,
	PHYSICS_ROPE_THIN = 0,
	PHYSICS_ROPE_DEFAULT = 1,
	PHYSICS_ROPE_DEFAULT_32 = 2,
	PHYSICS_ROPE_DEFAULT_WIRE = 3,
	PHYSICS_ROPE_THIN_WIRE_32 = 4,
	PHYSICS_ROPE_REINS = 5,
	PHYSICS_ROPE_THIN4 = 6,
}

--- ~>								 Damping Types								<~
---@class PHYSICS_DAMPING_TYPE
PHYSICS_DAMPING_TYPE = {
	PHYSICS_DAMPING_LINEAR_C = 0,
	PHYSICS_DAMPING_LINEAR_V = 1,
	PHYSICS_DAMPING_LINEAR_V2 = 2,
	PHYSICS_DAMPING_ANGULAR_C = 3,
	PHYSICS_DAMPING_ANGULAR_V = 4,
	PHYSICS_DAMPING_ANGULAR_V2 = 5,
}

