---@class PAYMENT_REFUSED_REASON
PAYMENT_REFUSED_REASON = {
	PRR_UNKNOWN = 0,
	PRR_INVALID_AMOUNT = 1, -- Amount is negative or 0
	PRR_NOT_ENOUGH_CASH = 2, -- Not enough Cash in the Wallet
	PRR_NOT_ENOUGH_EVC = 3, -- Not enough Earn Cash
	PRR_INVALID_BOOSID = 4, -- No boss Id set
}

--- PURPOSE: Player earned cash from a vehicle sell.
---@class SELLING_VEHICLE_TYPE
SELLING_VEHICLE_TYPE = {
	SVT_EARN_FROM_VEHICLE = 0,
	SVT_EARN_FROM_PERSONAL_NORMAL_VEHICLE = 1,
	SVT_EARN_FROM_PERSONAL_HIGHEND_VEHICLE = 2,
	SVT_EARN_FROM_PERSONAL_WEAPON_VEHICLE = 3,
	SVT_EARN_FROM_PERSONAL_AIRCRAFT_VEHICLE = 4,
	SVT_EARN_FROM_H2_WEAPONIZED_VEHICLE = 5,
	SVT_EARN_FROM_BATTLES_WEAPONIZED_VEHICLE = 6,
}

--- 
--- Spend events
--- 
---@class SPEND_CATEGORIES
SPEND_CATEGORIES = {
	MONEY_SPENT_WEAPON_ARMOR = GetHashKey("MONEY_SPENT_WEAPON_ARMOR"),
	MONEY_SPENT_VEH_MAINTENANCE = GetHashKey("MONEY_SPENT_VEH_MAINTENANCE"),
	MONEY_SPENT_CONTACT_SERVICE = GetHashKey("MONEY_SPENT_CONTACT_SERVICE"),
	MONEY_SPENT_STYLE_ENT = GetHashKey("MONEY_SPENT_STYLE_ENT"),
	MONEY_SPENT_PROPERTY_UTIL = GetHashKey("MONEY_SPENT_PROPERTY_UTIL"),
	MONEY_SPENT_JOB_ACTIVITY = GetHashKey("MONEY_SPENT_JOB_ACTIVITY"),
	MONEY_SPENT_BETTING = GetHashKey("MONEY_SPENT_BETTING"),
	MONEY_SPENT_HEALTHCARE = GetHashKey("MONEY_SPENT_HEALTHCARE"),
	MONEY_SPENT_FROM_DEBUG = GetHashKey("MONEY_SPENT_FROM_DEBUG"),
	MONEY_SPENT_DROPPED_STOLEN = GetHashKey("MONEY_SPENT_DROPPED_STOLEN"),
	MONEY_SPENT_HOLDUPS = GetHashKey("MONEY_SPENT_HOLDUPS"),
	MONEY_SPENT_PASSIVEMODE = GetHashKey("MONEY_SPENT_PASSIVEMODE"),
	MONEY_SPENT_BANKINTEREST = GetHashKey("MONEY_SPENT_BANKINTEREST"),
	MONEY_SPENT_ROCKSTAR_AWARD = GetHashKey("MONEY_SPENT_ROCKSTAR_AWARD"),
	MONEY_SPENT_NOCOPS = GetHashKey("MONEY_SPENT_NOCOPS"),
	MONEY_SPEND_DEDUCT = GetHashKey("MONEY_SPEND_DEDUCT"),
	MONEY_SPEND_BOSS_GOON = GetHashKey("MONEY_SPEND_BOSS_GOON"),
}

---@class EARN_CATEGORIES
EARN_CATEGORIES = {
	MONEY_EARN_JOBS = GetHashKey("MONEY_EARN_JOBS"),
	MONEY_EARN_SELLING_VEH = GetHashKey("MONEY_EARN_SELLING_VEH"),
	MONEY_EARN_BETTING = GetHashKey("MONEY_EARN_BETTING"),
	MONEY_EARN_GOOD_SPORT = GetHashKey("MONEY_EARN_GOOD_SPORT"),
	MONEY_EARN_PICKED_UP = GetHashKey("MONEY_EARN_PICKED_UP"),
	MONEY_EARN_SHARED = GetHashKey("MONEY_EARN_SHARED"),
	MONEY_EARN_JOBSHARED = GetHashKey("MONEY_EARN_JOBSHARED"),
	MONEY_EARN_ROCKSTAR_AWARD = GetHashKey("MONEY_EARN_ROCKSTAR_AWARD"),
	MONEY_EARN_REFUND = GetHashKey("MONEY_EARN_REFUND"),
	MONEY_EARN_BANK_INT = GetHashKey("MONEY_EARN_BANK_INT"),
	MONEY_EARN_BANK_INTEREST = GetHashKey("MONEY_EARN_BANK_INTEREST"),
	MONEY_EARN_FROM_JOB_BONUS = GetHashKey("MONEY_EARN_FROM_JOB_BONUS"),
	MONEY_EARN_FROM_HEIST_JOB = GetHashKey("MONEY_EARN_FROM_HEIST_JOB"),
}

---@class PURCHASE_TYPE
PURCHASE_TYPE = {
	PURCHASE_WEAPONS = 0,
	PURCHASE_WEAPONMODS = 1,
	PURCHASE_WEAPONAMMO = 2,
	PURCHASE_ARMOR = 3,
	PURCHASE_BARBERS = 4,
	PURCHASE_CLOTHES = 5,
	PURCHASE_TATTOOS = 6,
	PURCHASE_VEHICLES = 7,
	PURCHASE_CARMODS = 8,
	PURCHASE_CARINSURANCE = 9,
	PURCHASE_CARDROPOFF = 10,
	PURCHASE_CARREPAIR = 11,
	PURCHASE_FOOD = 12,
	PURCHASE_MASKS = 13,
	PURCHASE_CARIMPOUND = 14,
	PURCHASE_CARPAINT = 15,
	PURCHASE_CARWHEELMODS = 16,
	PURCHASE_FIREWORKS = 17,
	PURCHASE_ENDMISSIONCARUP = 18,
	PURCHASE_CASHEISTMISVEHUP = 19,
}

--- PURPOSE: Differentiates between the following types of expenditures: Lap dance, Watching the pole and Drinking at the bar.
---@class eStripClubExpenditureType
eStripClubExpenditureType = {
	LAP_DANCE = 0,
	WATCHING_THE_POLE = 1,
	DRINKING_AT_THE_BAR = 2,
}

---@class GANGOPS_AWARD_TYPE
GANGOPS_AWARD_TYPE = {
	GANGOPS_AWARD_MASTERMIND_2 = 0,
	GANGOPS_AWARD_MASTERMIND_3 = 1,
	GANGOPS_AWARD_MASTERMIND_4 = 2,
	GANGOPS_AWARD_LOYALTY_AWARD_2 = 3,
	GANGOPS_AWARD_LOYALTY_AWARD_3 = 4,
	GANGOPS_AWARD_LOYALTY_AWARD_4 = 5,
	GANGOPS_AWARD_FIRST_TIME_XM_BASE = 6,
	GANGOPS_AWARD_FIRST_TIME_XM_SUBMARINE = 7,
	GANGOPS_AWARD_FIRST_TIME_XM_SILO = 8,
	GANGOPS_AWARD_SUPPORTING = 9,
	GANGOPS_AWARD_ORDER = 10,
}

---@class GANGOPS_ELITE_TYPE
GANGOPS_ELITE_TYPE = {
	GANGOPS_ELITE_XM_BASE = 0,
	GANGOPS_ELITE_XM_SUBMARINE = 1,
	GANGOPS_ELITE_XM_SILO = 2,
}

---@class MEMBERSHIP_PURCHASE_METHOD
MEMBERSHIP_PURCHASE_METHOD = {
	MEMBERSHIP_PURCHASE_WEBSITE = GetHashKey("MEMBERSHIP_PURCHASE_WEBSITE"),
	MEMBERSHIP_PURCHASE_MIMI = GetHashKey("MEMBERSHIP_PURCHASE_MIMI"),
}

