--- PURPOSE: This structure contains the possible codes for the save migration.
---@class SAVEMIGRATION_PLATFORM_GENERATION
SAVEMIGRATION_PLATFORM_GENERATION = {
	SAVEMIGRATION_PLATFORM_NONE = 0,
	SAVEMIGRATION_PLATFORM_GEN8 = 8,
	SAVEMIGRATION_PLATFORM_GEN9 = 9,
}

--- PURPOSE: This structure contains the possible codes for the save migration.
---@class SAVEMIGRATION_STATUS_CODES
SAVEMIGRATION_STATUS_CODES = {
	SAVEMIGRATION_STATUS_NONE = 0,
	SAVEMIGRATION_STATUS_OK = 1,
	SAVEMIGRATION_STATUS_PENDING = 2,
	SAVEMIGRATION_STATUS_INPROGRESS = 3,
	SAVEMIGRATION_STATUS_TIMEOUT = 4,
	SAVEMIGRATION_STATUS_CANCELED = 5,
	SAVEMIGRATION_STATUS_ROLLEDBACK = 6,
	SAVEMIGRATION_STATUS_ERROR = 7,
}

--- PURPOSE: This structure contains the possible codes for the save migration.
---@class SAVEMIGRATION_STATUS_CODES
SAVEMIGRATION_STATUS_CODES = {
	SAVEMIGRATION_STATUS_NONE = 0,
	SAVEMIGRATION_STATUS_OK = 1,
	SAVEMIGRATION_STATUS_PENDING = 2,
	SAVEMIGRATION_STATUS_INPROGRESS = 3,
	SAVEMIGRATION_STATUS_CANCELED = 4,
	SAVEMIGRATION_STATUS_ROLLEDBACK = 5,
	SAVEMIGRATION_STATUS_ERROR = 6,
}

