--- List of weapon skill levels - must match the eWeaponSkill enumerated type in
--- weaponinfo.h in the games Weapons directory
---@class WEAPON_SKILLS
WEAPON_SKILLS = {
	WEAPONSKILL_POOR = 0,
	WEAPONSKILL_STD = 1,
	WEAPONSKILL_PRO = 2,
}

---@class VEHICLE_SELECTED_WEAPONS
VEHICLE_SELECTED_WEAPONS = {
	SELECTEDWEAPON_NONE = 0,
	SELECTEDWEAPON_GUNS = 1, -- 1
	SELECTEDWEAPON_BOMBS = 2, -- 2
	SELECTEDWEAPON_HSMISSILES = 3, -- 3
	SELECTEDWEAPON_MISSILES = 4, -- 4
}

--- Keep in sync with VehicleResourceFlags in VehicleScriptResource.h
---@class WEAPON_RESOURCE_FLAGS
WEAPON_RESOURCE_FLAGS = {
	WRF_REQUEST_BASE_ANIMS = 1,
	WRF_REQUEST_COVER_ANIMS = 2,
	WRF_REQUEST_MELEE_ANIMS = 4,
	WRF_REQUEST_MOTION_ANIMS = 8,
	WRF_REQUEST_STEALTH_ANIMS = 16,
	WRF_REQUEST_ALL_MOVEMENT_VARIATION_ANIMS = 32,
	WRF_REQUEST_ALL_ANIMS = 31,
}

---@class EXTRA_WEAPON_COMPONENT_RESOURCE_FLAGS
EXTRA_WEAPON_COMPONENT_RESOURCE_FLAGS = {
	WEAPON_COMPONENT_NONE = 0,
	WEAPON_COMPONENT_FLASH = 1,
	WEAPON_COMPONENT_SCOPE = 2,
	WEAPON_COMPONENT_SUPP = 4,
	WEAPON_COMPONENT_SCLIP2 = 8,
	WEAPON_COMPONENT_GRIP = 16,
}

