--- PURPOSE: Game options - these should not be set to QUERY_CRITERIA_ANY
---@class NETWORK_GAME_OPTIONS_BASIC
NETWORK_GAME_OPTIONS_BASIC = {
	GAME_OPTION_BASIC_GAME_MODE = 0,
	GAME_OPTION_BASIC_IS_RANKED = 1,
	GAME_OPTION_BASIC_NUM_SLOTS = 2,
	GAME_OPTION_BASIC_NUM_PRIV_SLOTS = 3,
	GAME_OPTION_BASIC_EPISODE = 4,
	GAME_OPTION_BASIC_TEAM_GAME = 5,
	GAME_OPTION_BASIC_NUM_OPTIONS = 6,
}

--- Status returned from PROFILE STATS READ operation.
---@class NETWORK_PROFILE_STATS_STATUS
NETWORK_PROFILE_STATS_STATUS = {
	NET_PS_IDLE = 0,
	NET_PS_PENDING = 1,
	NET_PS_SUCCESS = 2,
	NET_PS_FAILED = 3,
}

--- PURPOSE: Game options - these should not be set to QUERY_CRITERIA_ANY
---@class NETWORK_ROS_PRIVILEGEID
NETWORK_ROS_PRIVILEGEID = {
	RLROS_PRIVILEGEID_NONE = 0, -- Unused
	RLROS_PRIVILEGEID_CREATE_TICKET = 1, -- Can create ROS tickets
	RLROS_PRIVILEGEID_PROFILE_STATS_WRITE = 2, -- Can write profile stats
	RLROS_PRIVILEGEID_MULTIPLAYER = 3, -- Can participate in MP sessions (currently not used)
	RLROS_PRIVILEGEID_LEADERBOARD_WRITE = 4, -- Can write to leaderboards (currently not used)
	RLROS_PRIVILEGEID_CLOUD_STORAGE_READ = 5, -- Can write to cloud storage
	RLROS_PRIVILEGEID_CLOUD_STORAGE_WRITE = 6, -- Can read from cloud storage
	RLROS_PRIVILEGEID_BANNED = 7, -- Denies all other privileges except CREATE_TICKET
	RLROS_PRIVILEGEID_CLAN = 8, -- Can use clan functions
	RLROS_PRIVILEGEID_PRIVATE_MESSAGING = 9, -- Can use private messaging system
	RLROS_PRIVILEGEID_SOCIAL_CLUB = 10, -- Can login to SC site, and TBD other functionality
	RLROS_PRIVILEGEID_PRESENCE_WRITE = 11, -- Can update presence
	RLROS_PRIVILEGEID_DEVELOPER = 12, -- If true, user is considered a developer
	RLROS_PRIVILEGEID_HTTP_REQUEST_LOGGING = 13, -- If true, user's HTTP request log to SCS gameservices and cloud is logged
	RLROS_PRIVILEGEID_UGCWRITE = 14, -- If true, allows writing UGC
	RLROS_PRIVILEGEID_PURCHASEVC = 15, -- If true, allows purchasing virtual currency
	RLROS_PRIVILEGEID_TRANSFERVC = 16, -- If true, allows transferring virtual currency
	RLROS_PRIVILEGEID_CANBET = 17, -- If true, player can place bets
	RLROS_PRIVILEGEID_CREATORS = 18, -- If true, player can access the creators
	RLROS_PRIVILEGEID_CLOUD_TUNABLES = 19, -- If true, player can download the cloud tunables
	RLROS_PRIVILEGEID_CHEATER_POOL = 20, -- If true, player is in the cheater pool
	RLROS_PRIVILEGEID_COMMENTWRITE = 21, -- If true, user can create comments
	RLROS_PRIVILEGEID_CANUSELOTTERY = 22, -- If true, player can buy lottery tickets
	RLROS_PRIVILEGEID_ALLOW_MEMBER_REDIRECT = 23, -- If true, player should run member space re-directs
	RLROS_PRIVILEGEID_PLAYED_LAST_GEN = 24, -- If true, grant played last gen privilege
	RLROS_PRIVILEGEID_UNLOCK_SPECIAL_EDITION = 25, -- If true, grant special edition content
	RLROS_NUM_PRIVILEGEID = 26,
}

---@class NETWORK_SCRIPT_STATE
NETWORK_SCRIPT_STATE = {
	NETSCRIPT_NOT_ACTIVE = 0,
	NETSCRIPT_JOINING = 1,
	NETSCRIPT_PLAYING = 2,
	NETSCRIPT_TERMINATED = 3,
	NETSCRIPT_FAILED_SESSION_FULL = 4,
	NETSCRIPT_FAILED_NO_JOIN_IN_PROGRESS = 5,
	NETSCRIPT_FAILED_TEAM_FULL = 6,
}

--- /PURPOSE: Enum describing reasons for NETWORK_CAN_ACCESS_MULTIPLAYER
---@class MULTIPLAYER_ACCESS_CODE
MULTIPLAYER_ACCESS_CODE = {
	ACCESS_GRANTED = 0,
	ACCESS_DENIED_TUNABLE_NOT_FOUND = 1,
	ACCESS_DENIED_TUNABLE_FALSE = 2,
	ACCESS_DENIED_NETWORK_LOCKED = 3,
	ACCESS_DENIED_INVALID_PROFILE_SETTINGS = 4,
	ACCESS_DENIED_PROLOGUE_INCOMPLETE = 5,
	ACCESS_DENIED_NOT_SIGNED_IN = 6,
	ACCESS_DENIED_NOT_SIGNED_ONLINE = 7,
	ACCESS_DENIED_NO_ONLINE_PRIVILEGE = 8,
	ACCESS_DENIED_NO_SCS_CREDENTIALS = 9,
	ACCESS_DENIED_NO_SCS_PRIVILEGE = 10,
	ACCESS_DENIED_MULTIPLAYER_DISABLED = 11,
	ACCESS_DENIED_NO_TUNABLES = 12,
	ACCESS_DENIED_NO_BACKGROUND_SCRIPT = 13,
}

--- /PURPOSE: NAT types.
---@class NET_NAT_TYPE
NET_NAT_TYPE = {
	NET_NAT_UNKNOWN = 0,
	NET_NAT_OPEN = 1,
	NET_NAT_MODERATE = 2,
	NET_NAT_STRICT = 3,
	NET_NAT_NUM_TYPES = 4,
}

--- PURPOSE: Matchmaking Value type
---@class MATCHMAKING_VALUE
MATCHMAKING_VALUE = {
	MM_ATTR_AIM_TYPE = 0,
}

--- PURPOSE: Matchmaking Query type
---@class MATCHMAKING_QUERY_TYPE
MATCHMAKING_QUERY_TYPE = {
	MQ_FRIENDS = 0,
	MQ_SOCIAL = 1,
	MQ_PLATFORM = 2,
}

--- PURPOSE: Matchmaking
---@class MATCHMAKING_QUERY
MATCHMAKING_QUERY = {
	MQ_GENERAL = 0,
	MQ_CNC = 1,
}

--- PURPOSE: Network start session type.
---@class NETWORK_AUTO_START_TYPE
NETWORK_AUTO_START_TYPE = {
	AUTOSTART_NONE = 0,
	AUTOSTART_JOIN_MATCH = 1,
	AUTOSTART_JOIN_ROOM = 2,
	AUTOSTART_HOST = 3,
	AUTOSTART_SEAMLESS = 4,
}

--- PURPOSE: Matchmaking groups. Groups within the maximum player pool.
---@class MATCHMAKING_GROUP
MATCHMAKING_GROUP = {
	MM_GROUP_FREEMODER = 0,
	MM_GROUP_COP = 1,
	MM_GROUP_VAGOS = 2,
	MM_GROUP_LOST = 3,
	MM_GROUP_SCTV = 4,
}

--- PURPOSE: Privilege Check Type
---@class PRIVILEGE_CHECK
PRIVILEGE_CHECK = {
	PC_EVERYONE = 0,
	PC_FRIENDS = 1,
}

--- Except for PED_CLASSIFICATION_ANY These enums must be the same ePedType in PedTypes.h
---@class PED_CLASSIFICATION
PED_CLASSIFICATION = {
	PED_CLASSIFICATION_CIVMALE = 0,
	PED_CLASSIFICATION_CIVFEMALE = 1,
	PED_CLASSIFICATION_COP = 2,
	PED_CLASSIFICATION_GANG_ALBANIAN = 3,
	PED_CLASSIFICATION_GANG_BIKER_1 = 4,
	PED_CLASSIFICATION_GANG_BIKER_2 = 5,
	PED_CLASSIFICATION_GANG_ITALIAN = 6,
	PED_CLASSIFICATION_GANG_RUSSIAN = 7,
	PED_CLASSIFICATION_GANG_RUSSIAN_2 = 8,
	PED_CLASSIFICATION_GANG_IRISH = 9,
	PED_CLASSIFICATION_GANG_JAMAICAN = 10,
	PED_CLASSIFICATION_GANG_AFRICAN_AMERICAN = 11,
	PED_CLASSIFICATION_GANG_KOREAN = 12,
	PED_CLASSIFICATION_GANG_CHINESE_JAPANESE = 13,
	PED_CLASSIFICATION_GANG_PUERTO_RICAN = 14,
	PED_CLASSIFICATION_DEALER = 15,
	PED_CLASSIFICATION_MEDIC = 16,
	PED_CLASSIFICATION_FIRE = 17,
	PED_CLASSIFICATION_CRIMINAL = 18,
	PED_CLASSIFICATION_BUM = 19,
	PED_CLASSIFICATION_PROSTITUTE = 20,
	PED_CLASSIFICATION_SPECIAL = 21,
	PED_CLASSIFICATION_MISSION = 22,
	PED_CLASSIFICATION_SWAT = 23,
	PED_CLASSIFICATION_ANY = 24,
}

---@class RESPAWN_QUERY_FLAGS
RESPAWN_QUERY_FLAGS = {
	RESPAWN_QUERY_FLAG_DEFAULT = 0,
	RESPAWN_QUERY_FLAG_IGNORE_TARGET_HEADING = 2,
	RESPAWN_QUERY_FLAG_PREFER_CLOSE_TO_SPAWN_ORIGIN = 4,
	RESPAWN_QUERY_FLAG_MAY_SPAWN_IN_INTERIOR = 8,
	RESPAWN_QUERY_FLAG_MAY_SPAWN_IN_EXTERIOR = 16,
	RESPAWN_QUERY_FLAG_PREFER_WIDE_FOV = 32,
	RESPAWN_QUERY_FLAG_PREFER_TEAM_BUNCHING = 64,
	RESPAWN_QUERY_FLAG_PREFER_ENEMY_PLAYERS_FARTHER = 128,
	RESPAWN_QUERY_FLAG_PREFER_FRIENDLY_PLAYERS_CLOSER = 256,
	RESPAWN_QUERY_FLAG_PREFER_ENEMY_AI_FARTHER = 512,
	RESPAWN_QUERY_FLAG_PREFER_FRIENDLY_AI_CLOSER = 1024,
	RESPAWN_QUERY_FLAG_PREFER_RANDOMNESS = 2048,
}

---@class RESPAWN_RESULT_FLAGS
RESPAWN_RESULT_FLAGS = {
	RESPAWN_RESULT_FLAG_DEFAULT = 0,
	RESPAWN_RESULT_FLAG_PAVEMENT = 1,
	RESPAWN_RESULT_FLAG_INTERIOR = 2,
}

---@class RESPAWN_QUERY_RESULTS
RESPAWN_QUERY_RESULTS = {
	RESPAWN_QUERY_RESULTS_FAILED = 0,
	RESPAWN_QUERY_RESULTS_SUCCEEDED = 1,
	RESPAWN_QUERY_RESULTS_STILL_WORKING = 2,
	RESPAWN_QUERY_RESULTS_NO_SEARCH_ACTIVE = 3,
}

--- for NETWORK_BROADCAST_FRIEND_MSG
---@class FRIENDMSG_TYPE
FRIENDMSG_TYPE = {
	FRIENDMSG_TYPE_TEXTLABEL = 0,
	FRIENDMSG_TYPE_TEXTLABEL_WITH_INT = 1,
}

--- for NETWORK_GET_GAME_REGION
---@class RL_GAME_REGION
RL_GAME_REGION = {
	RL_GAME_REGION_INVALID = -1,
	RL_GAME_REGION_AMERICA = 0,
	RL_GAME_REGION_EUROPE = 1,
	RL_GAME_REGION_JAPAN = 2,
}

--- for UGC This must match eUserGeneratedContentType in commands_network.cpp
---@class UGC_TYPE
UGC_TYPE = {
	UGC_TYPE_GTA5_MISSION = 0,
	UGC_TYPE_GTA5_MISSION_PLAYLIST = 1,
	UGC_TYPE_GTA5_LIFE_INVADER_POST = 2,
	UGC_TYPE_GTA5_PHOTO = 3,
	UGC_TYPE_GTA5_CHALLENGE = 4,
}

---@class UGC_CATEGORY
UGC_CATEGORY = {
	UGC_CATEGORY_NONE = 0,
	UGC_CATEGORY_ROCKSTAR_CREATED = 1,
	UGC_CATEGORY_ROCKSTAR_CREATED_CANDIDATE = 2,
	UGC_CATEGORY_ROCKSTAR_VERIFIED = 3,
	UGC_CATEGORY_ROCKSTAR_VERIFIED_CANDIDATE = 4,
	UGC_CATEGORY_ROCKSTAR_COMMUNITY = 5,
	UGC_CATEGORY_ROCKSTAR_COMMUNITY_CANDIDATE = 6,
}

---@class UGC_ERROR
UGC_ERROR = {
	UGC_ERROR_UNEXPECTED_RESULT = -1,
	UGC_ERROR_NONE = 0,
	UGC_ERROR_AUTHENTICATIONFAILED_TICKET = 1,
	UGC_ERROR_DOESNOTEXIST_CONTENT = 2,
	UGC_ERROR_DOESNOTEXIST_PUBLISHER = 3,
	UGC_ERROR_INVALIDARGUMENT_CLOUDABSPATH = 4,
	UGC_ERROR_INVALIDARGUMENT_CONTENTID = 5,
	UGC_ERROR_INVALIDARGUMENT_CONTENTNAME = 6,
	UGC_ERROR_INVALIDARGUMENT_CONTENTTYPE = 7,
	UGC_ERROR_INVALIDARGUMENT_ONLINESERVICE = 8,
	UGC_ERROR_INVALIDARGUMENT_TAGS = 9,
	UGC_ERROR_INVALIDARGUMENT_TITLEINFO = 10,
	UGC_ERROR_INVALIDARGUMENT_USERID = 11,
	UGC_ERROR_NOTALLOWED_MAXCREATED = 12,
	UGC_ERROR_NOTALLOWED_NOTCONTENTOWNER = 13,
	UGC_ERROR_NOTALLOWED_NOTLATEST = 14,
	UGC_ERROR_NOTALLOWED_PROFANE = 15,
	UGC_ERROR_NOTALLOWED_RESERVEDWORD = 16,
	UGC_ERROR_OUTOFRANGE_CONTENTTYPE = 17,
}

--- Keep enum in sync with NetworkHasherUtil.h
--- Used to perform CRC checks between players. On each system check we need to define what part of it is being compared.
--- For instance, for a Weapons system only one weapon will be compared {system=CRC_ITEM_INFO_DATA, subsystem=hash(weaponName)}.
--- That's defined as their subsystem into a single INT, which will behave differently depending on the hashable_system required.
---@class HASHABLE_SYSTEM
HASHABLE_SYSTEM = {
	CRC_TUNING_SYSTEM = 0, -- < DO NOT USE DIRECTLY. Use TRIGGER_TUNING_CRC_HACKER_CHECK wrapper instead
	CRC_ITEM_INFO_DATA = 1, -- < subsystem can be any CItemInfo name hash (includes WEAPON_TYPE weapon hash and CAmmoInfo item hash)
	CRC_PICKUP_INFO_DATA = 2, -- < subsystem has to be a PICKUP_TYPE (hash of a CPickupData)
	CRC_EXPLOSION_TAG_DATA = 3, -- < subsystem has to be an EXPLOSION_TAG
	CRC_DATA_FILE_CONTENTS = 4, -- < DO NOT USE DIRECTLY. Use TRIGGER_FILE_CRC_HACKER_CHECK wrapper instead
	CRC_GENERIC_FILE_CONTENTS = 5, -- < DO NOT USE DIRECTLY. Use TRIGGER_FILE_CRC_HACKER_CHECK wrapper instead
	CRC_SCRIPT_RESOURCE = 6, -- < subsystem has to be a a script name hash (for instance HASH("freemode"))
}

---@class GAMER_STATUS
GAMER_STATUS = {
	GAMER_STATUS_INVALID = -1,
	GAMER_STATUS_IN_TITLE = 0,
	GAMER_STATUS_IN_TITLE_MP = 1,
	GAMER_STATUS_OFF_TITLE = 2,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_VOICE_CONNECTION_REQUESTED.
--- - EVENT_VOICE_CONNECTION_RESPONSE.
--- - EVENT_VOICE_CONNECTION_TERMINATED.
---@class CONNECTION_RESPONSE_TYPES
CONNECTION_RESPONSE_TYPES = {
	RESPONSE_ACCEPTED = 0,
	RESPONSE_REJECTED = 1,
	RESPONSE_BUSY = 2,
	RESPONSE_TIMED_OUT = 3,
	RESPONSE_ERROR = 4,
	RESPONSE_BLOCKED = 5,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_SESSION_EVENT.
---@class SESSION_EVENT_TYPE
SESSION_EVENT_TYPE = {
	EVENT_SESSION_MIGRATE_END = 0,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_TRANSITION_EVENT.
---@class TRANSITION_EVENT_TYPE
TRANSITION_EVENT_TYPE = {
	EVENT_TRANSITION_HOSTING = 0,
	EVENT_TRANSITION_HOSTED = 1,
	EVENT_TRANSITION_HOST_FAILED = 2,
	EVENT_TRANSITION_JOINING = 3,
	EVENT_TRANSITION_JOINED = 4,
	EVENT_TRANSITION_JOINED_LAUNCHED = 5,
	EVENT_TRANSITION_JOIN_FAILED = 6, -- nEventParam corresponds to JOIN_RESPONSE_CODE
	EVENT_TRANSITION_STARTING = 7,
	EVENT_TRANSITION_STARTED = 8,
	EVENT_TRANSITION_ENDING = 9,
	EVENT_TRANSITION_ENDED = 10,
	EVENT_TRANSITION_QUICKMATCH = 11,
	EVENT_TRANSITION_QUICKMATCH_JOINING = 12,
	EVENT_TRANSITION_QUICKMATCH_HOSTING = 13,
	EVENT_TRANSITION_START_LAUNCH = 14,
	EVENT_TRANSITION_END_LAUNCH = 15,
	EVENT_TRANSITION_KICKED = 16,
	EVENT_TRANSITION_ERROR = 17,
	EVENT_TRANSITION_MIGRATE_START = 18,
	EVENT_TRANSITION_MIGRATE_END = 19,
	EVENT_TRANSITION_TO_GAME_START = 20,
	EVENT_TRANSITION_TO_GAME_JOINING = 21,
	EVENT_TRANSITION_TO_GAME_JOINED = 22,
	EVENT_TRANSITION_TO_GAME_HOSTING = 23,
	EVENT_TRANSITION_TO_GAME_FINISH = 24,
	EVENT_TRANSITION_QUICKMATCH_FAILED = 25,
	EVENT_TRANSITION_QUICKMATCH_TIMEOUT = 26,
	EVENT_TRANSITION_GROUP_QUICKMATCH_STARTED = 27, -- hGamer corresponds to group leader
	EVENT_TRANSITION_GROUP_QUICKMATCH_FINISHED = 28, -- hGamer corresponds to group leader, nEventParam is 1 if we have a valid session
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_SESSION_END
---@class END_REASON
END_REASON = {
	END_NORMAL = 0,
	END_TRANSITION_LAUNCH = 1,
	END_PARTY_LEFT = 2,
	END_KICKED = 3,
	END_RESERVING_SLOT = 4,
	END_ERROR = 5,
	END_KICKED_ADMIN = 6,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_PRESENCE_INVITE_REMOVED
---@class INVITE_REMOVE_REASON
INVITE_REMOVE_REASON = {
	REMOVE_TIMED_OUT = 0,
	REMOVE_OLDEST = 1,
	REMOVE_CANCELLED = 2,
	REMOVE_ACCEPTED = 3,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_PRESENCE_INVITE_REPLY
---@class INVITE_STATUS
INVITE_STATUS = {
	INVITESTATUS_NONE = 0,
	INVITESTATUS_IN_SINGLE_PLAYER = 1,
	INVITESTATUS_IN_FREEMODE = 2,
	INVITESTATUS_IN_CORONA = 3,
	INVITESTATUS_IN_ACTIVITY = 4,
	INVITESTATUS_CANNOT_ACCESS_MULTIPLAYER = 5,
	INVITESTATUS_NO_PRIVILEGE = 6,
	INVITESTATUS_BLOCKED = 7,
	INVITESTATUS_BLOCKED_INACTIVE = 8,
	INVITESTATUS_CHEATER = 9,
	INVITESTATUS_BAD_SPORT = 10,
	INVITESTATUS_CANNOT_PROCESS_PRESENCE = 11,
	INVITESTATUS_IN_STORE = 12,
	INVITESTATUS_IN_CREATOR = 13,
	INVITESTATUS_INACTIVE = 14,
	INVITESTATUS_FROM_JOIN_QUEUE = 15,
	INVITESTATUS_IN_SESSION = 16,
	INVITESTATUS_INCOMPATIBLE = 17,
	INVITESTATUS_IN_EDITOR = 18,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_APP_LAUNCHED
---@class APP_LAUNCH_FLAGS
APP_LAUNCH_FLAGS = {
	LAUNCH_STRAIGHT_INTO_FREEMODE = 0,
	LAUNCH_FROM_LIVE_AREA = 1,
	LAUNCH_DIRECT_TO_CONTENT = 2,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_SYSTEM_SERVICE_EVENT
--- Either add a CompileTimeAssert in code for these assignments or build a
--- script specific index and convert from code
---@class SYSTEM_SERVICE_EVENT_ID
SYSTEM_SERVICE_EVENT_ID = {
	EVENT_SUSPENDED = 2,
	EVENT_RESUMING = 4,
	EVENT_INVITATION_RECEIVED = 24,
	EVENT_APP_LAUNCHED = 30,
}

--- PURPOSE: This structure can be used to retrieve information from these events:
--- - EVENT_NETWORK_CLOUD_EVENT
---@class CLOUD_EVENT_ID
CLOUD_EVENT_ID = {
	CLOUD_EVENT_TUNABLES_ADDED = 0,
	CLOUD_EVENT_BGSCRIPT_ADDED = 1,
}

--- code: eMileStoneId
---@class MILESTONE_ID
MILESTONE_ID = {
	FACEBOOK_MILESTONE_CHECKLIST = 0, -- 100%% Complete game.
	FACEBOOK_MILESTONE_OVERVIEW = 1, -- 100%% Complete story mission.
	FACEBOOK_MILESTONE_VEHICLES = 2, -- Driven all cars.
	FACEBOOK_MILESTONE_PROPERTIES = 3, -- Bought all properties.
	FACEBOOK_MILESTONE_PSYCH = 4, -- Future: psych report (TBD)
	FACEBOOK_MILESTONE_MAPREVEAL = 5, -- Map reveal
	FACEBOOK_MILESTONE_PROLOGUE = 6, -- Prologue completed
}

--- PURPOSE: Flags for Matchmaking
---@class MM_FLAGS
MM_FLAGS = {
	MM_FLAGS_NONE = 0,
	MM_FLAG_ASYNCHRONOUS = BIT0,
	MM_FLAG_QUICKMATCH = BIT1,
	MM_FLAG_ALLOW_BLACKLISTED = BIT2,
	MM_FLAG_DISABLE_ANY_JOB_QUERIES = BIT6, -- < jobs only
	MM_FLAG_DISABLE_IN_PROGRESS_QUERIES = BIT7, -- < jobs only
	MM_FLAG_ROCKSTAR_CONTENT_ONLY = BIT9, -- < jobs only
	MM_FLAG_USER_CONTENT_ONLY = BIT10, -- < jobs only
	MM_FLAG_IS_BOSS = BIT11,
	MM_FLAG_JOB_TO_JOB = BIT12, -- < to_game only
	MM_FLAG_BAIL_FROM_LAUNCHED_JOBS = BIT14, -- < jobs only
	MM_FLAG_ONLY_IN_PROGRESS = BIT15, -- < jobs only
	MM_FLAG_TO_GAME_VIA_TRANSITION = BIT16, -- < to_game only
	MM_FLAG_EXPANDED_INTRO_FLOW = BIT17,
}

--- PURPOSE: Flags for Hosting
---@class HOST_FLAGS
HOST_FLAGS = {
	HOST_FLAGS_NONE = 0,
	HOST_FLAG_JOB_TO_JOB = BIT13, -- < to_game only
	HOST_FLAG_ASYNCHRONOUS = BIT14, -- < transition only
	HOST_FLAG_PREMIUM = BIT15,
	HOST_FLAG_VIA_TRANSITION_LOBBY = BIT16, -- < to_game only
}

--- PURPOSE: Flags for Leaving
---@class LEAVE_FLAGS
LEAVE_FLAGS = {
	LEAVE_FLAGS_NONE = 0,
	LEAVE_FLAG_RETURN_TO_LOBBY = BIT0,
	LEAVE_FLAG_BLACKLIST_SESSION = BIT1,
	LEAVE_FLAG_NO_TRANSITION_BAIL = BIT2,
}

--- Script can edit this enum to include new values
--- This is defined to give code some context when we see different values show up in the logs
---@class ACTIVITY_ISLAND
ACTIVITY_ISLAND = {
	ACTIVITY_ISLAND_INVALID = -1,
	ACTIVITY_ISLAND_GENERAL = 0,
	ACTIVITY_ISLAND_SPECIFIC = 1,
	ACTIVITY_ISLAND_PLAYLIST = 2,
	ACTIVITY_ISLAND_EVENT = 3,
	ACTIVITY_ISLAND_TOURNAMENT = 4,
}

---@class JOB_CONTENT_CREATOR
JOB_CONTENT_CREATOR = {
	JOB_CONTENT_ROCKSTAR_CREATED = 0,
	JOB_CONTENT_USER_CREATED = 1,
}

---@class NETWORK_RESERVATION_TYPE
NETWORK_RESERVATION_TYPE = {
	RESERVATION_ALL = 0,
	RESERVATION_LOCAL_ONLY = 1,
	RESERVATION_GLOBAL_ONLY = 2,
}

---@class NP_UNAVAILABILITY_REASON
NP_UNAVAILABILITY_REASON = {
	REASON_INVALID = -1,
	REASON_OTHER = 0,
	REASON_SYSTEM_UPDATE = 1,
	REASON_GAME_UPDATE = 2,
	REASON_SIGNED_OUT = 3,
	REASON_AGE = 4,
	REASON_CONNECTION = 5,
}

---@class RL_AGEGROUP
RL_AGEGROUP = {
	RL_AGEGROUP_INVALID = -1,
	RL_AGEGROUP_PENDING = 0, -- Age group is being retrieved.
	RL_AGEGROUP_CHILD = 1,
	RL_AGEGROUP_TEEN = 2,
	RL_AGEGROUP_ADULT = 3,
}

---@class SEND_INVITE_FLAGS
SEND_INVITE_FLAGS = {
	SEND_INVITE_FLAGS_NONE = 0,
	SEND_INVITE_FLAG_TRANSITION = BIT0,
	SEND_INVITE_FLAG_IMPORTANT = BIT1,
}

--- Need to match CardTypes in PlayerCardDataManager.h
---@class PLAYER_LIST_TYPE
PLAYER_LIST_TYPE = {
	PLAYER_LIST_TYPE_LAST_JOB = 100,
	PLAYER_LIST_TYPE_JOINED = 101,
	PLAYER_LIST_TYPE_CORONA_PLAYERS = 102,
	PLAYER_LIST_TYPE_INVITABLE_SESSION_PLAYERS = 103,
	PLAYER_LIST_TYPE_MATCHED_PLAYERS = 104,
	PLAYER_LIST_TYPE_CORONA_PLAYLIST = 105,
	PLAYER_LIST_TYPE_DIRECTORY = 106,
}

--- Needs to match eOnlineStatus in commands_network.cpp
---@class ONLINE_STATUS
ONLINE_STATUS = {
	OS_OFFLINE = 0,
	OS_ONLINE_ANOTHER_GAME = 1,
	OS_ONLINE_SP = 2,
	OS_ONLINE_MP = 3,
	OS_ONLINE_IN_LOCAL_SESSION = 4,
	OS_ONLINE_IN_LOCAL_TRANSITION = 5,
}

---@class UGC_BOOL_OPTION
UGC_BOOL_OPTION = {
	OPTION_NOT_SPECIFIED = 0,
	OPTION_TRUE = 1,
	OPTION_FALSE = 2,
}

---@class UGC_SORT_TYPE
UGC_SORT_TYPE = {
	SORT_NOT_SPECIFIED = -1,
	SORT_CREATED_DATE = 0,
}

--- Facebook
--- returned from FACEBOOK_GET_POST_RESULT_CODE()
---@class FACEBOOK_TYPE_ERROR
FACEBOOK_TYPE_ERROR = {
	FB_ERROR_OK = 0,
	FB_ERROR_NOACTIVEGAMER = 1,
	FB_ERROR_INVALIDLOCALGAMERIDX = 2,
	FB_ERROR_INVALIDACCESSTOKEN = 3,
	FB_ERROR_NOTSIGNEDIN = 4,
	FB_ERROR_OFFLINE = 5,
	FB_ERROR_GETACESSTOKEN = 6,
	FB_ERROR_POST = 7,
}

--- **************************************************************
--- Commerce enums
--- 
--- Candidate for splitting into a seperate script header in the future (hence being down here).
--- 
--- *****************************************************************
--- PURPOSE: Enum to be passed into SET_COMMERCE_STORE_BRANDING
---@class E_COMMERCE_STORE_BRANDING
E_COMMERCE_STORE_BRANDING = {
	CS_BRAND_NONE = 0,
	CS_BRAND_AMMUNATION = 1,
	CS_BRAND_PONSONBYS = 2,
	CS_BRAND_BOBMULLET = 3,
	CS_BRAND_PECKERWOOD = 4,
	CS_BRAND_BINCO = 5,
}

---@class E_PREMIUM_PACK_TYPE
E_PREMIUM_PACK_TYPE = {
	EPPT_NONE = 0,
	EPPT_STANDALONE = 1,
	EPPT_BUNDLED_WITH_GREAT_WHITE = 2,
	EPPT_BUNDLED_WITH_WHALE = 3,
	EPPT_BUNDLED_WITH_MEGALODON = 4,
}

--- Status returned from PROFILE STATS READ operation.
---@class STORE_PURCHASE_LOCATION
STORE_PURCHASE_LOCATION = {
	SPL_UNKNOWN = 0,
	SPL_SCUI = 1,
	SPL_INGAME = 2, -- Pause menu 'Store' tab
	SPL_STORE = 3, -- All insufficient fund alerts
	SPL_PHONE = 4, -- Contact requests
	SPL_AMBIENT = 5, -- Most ambient script systems
	SPL_ONLINE_TAB = 6, -- Pause menu 'Online' tab
	SPL_STORE_GUN = 7, -- Direct access from shop
	SPL_STORE_CLOTH = 8, -- Direct access from shop
	SPL_STORE_HAIR = 9, -- Direct access from shop
	SPL_STORE_CARMOD = 10, -- Direct access from shop
	SPL_STORE_TATTOO = 11, -- Direct access from shop
	SPL_STORE_PERSONAL_MOD = 12, -- Direct access from shop
	SPL_STARTER_PACK = 13, -- Pause menu 'Online' tab starter pack option
	SPL_LANDING_MP = 14, -- A landing page ol-menu button
	SPL_LANDING_SP_UPSELL = 15, -- The single player upsell page
	SPL_PRIORITY_FEED = 16, -- The priority feed
	SPL_WHATS_NEW = 17, -- the whats new feed
	SPL_MEMBERSHIP_INGAME = 18, --@notes CONDITION WAS CONVERTED AUTOMATICALLY; OLD CONDITION WAS: #IF FEATURE_GTAO_MEMBERSHIP ... #ENDIF
	SPL_UNUSED = 19, --@notes CONDITION WAS CONVERTED AUTOMATICALLY; OLD CONDITION WAS: #IF NOT FEATURE_GTAO_MEMBERSHIP ... #ENDIF
	SPL_PAUSE_PLAY_SP = 20, -- The play single player button from the MP pause menu when SP is not owned
	SPL_CHARACTER_SELECTION_WHEEL = 21, -- The character selection whell when SP is not owned
}

---@class PLAYER_REVIEW_MODE
PLAYER_REVIEW_MODE = {
	PLAYER_REVIEW_ALL_PLAYERS = 0,
	PLAYER_REVIEW_TEAM_ONLY = 1,
}

---@class UDS_UPDATE_MODE
UDS_UPDATE_MODE = {
	UDS_UPDATE_MODE_FULL = 0,
	UDS_UPDATE_MODE_DELTA = 1,
}

--- !!! DO NOT CHANGE THIS ORDER, DICTATED BY BACKEND SETUP !!!
---@class UDS_ACTIVITY_END_REASON
UDS_ACTIVITY_END_REASON = {
	UDS_ACTIVITY_END_REASON_NONE = 0,
	UDS_ACTIVITY_END_REASON_COMPLETED = 1,
	UDS_ACTIVITY_END_REASON_FAILED = 2,
	UDS_ACTIVITY_END_REASON_ABANDONED = 3,
}

---@class NET_SC_MEMBERSHIP_EVENT_TYPE
NET_SC_MEMBERSHIP_EVENT_TYPE = {
	MEMBERSHIP_EVENT_TYPE_STATUS_RECEIVED = 0,
	MEMBERSHIP_EVENT_TYPE_STATUS_CHANGED = 1,
}

---@class NET_SC_BENEFITS_EVENT_TYPE
NET_SC_BENEFITS_EVENT_TYPE = {
	BENEFITS_EVENT_TYPE_BENEFITS_CLAIMED = 0,
}

