---@class eMapChangeStates
eMapChangeStates = {
	MCS_INVALID = -1,
	MCS_NONE = 0,
	MCS_INIT = 1,
	MCS_UPDATE = 2,
	MCS_END = 3,
	MCS_COUNT = 4,
}

---@class eDlcCloudResult
eDlcCloudResult = {
	DLCRESULT_NOT_READY = -1,
	DLCRESULT_OK = 0,
	DLCRESULT_CONNECTION_ERROR = 1,
	DLCRESULT_TIMEOUT = 2,
	DLCRESULT_COUNT = 3,
}

---@class USER_ENTITLEMENT_STATUS
USER_ENTITLEMENT_STATUS = {
	USER_ENTITLEMENT_STATUS_UNKNOWN = 0,
	USER_ENTITLEMENT_STATUS_NONE = 1,
	USER_ENTITLEMENT_STATUS_ENTITLED = 2,
}

