---@class TRIGGER_METHOD
TRIGGER_METHOD = {
	TRIGGER_METHOD_ATTRACTOR = 0,
	TRIGGER_METHOD_AT_ATTRACTOR = 1,
	TRIGGER_METHOD_SCHEDULE = 2,
	TRIGGER_METHOD_SCHEDULE_ARRIVAL = 3,
	TRIGGER_METHOD_SCHEDULE_DEPARTURE = 4,
}

