---@class CORONATYPE
CORONATYPE = {
	CORONATYPE_SHINYSTAR = 0,
	CORONATYPE_MOON = 1,
	CORONATYPE_NONE = 2,
}

---@class FLARETYPE
FLARETYPE = {
	FLARETYPE_NONE = 0,
	FLARETYPE_SUN = 1,
	FLARETYPE_HEADLIGHTS = 2,
}

---@class CHECKPOINT_TYPE
CHECKPOINT_TYPE = {
	CHECKPOINT_RACE_GROUND_CHEVRON_1_BASE = 0,
	CHECKPOINT_RACE_GROUND_CHEVRON_2_BASE = 1,
	CHECKPOINT_RACE_GROUND_CHEVRON_3_BASE = 2,
	CHECKPOINT_RACE_GROUND_LAP_BASE = 3,
	CHECKPOINT_RACE_GROUND_FLAG_BASE = 4,
	CHECKPOINT_RACE_GROUND_PIT_LANE_BASE = 5,
	CHECKPOINT_RACE_GROUND_CHEVRON_1 = 6,
	CHECKPOINT_RACE_GROUND_CHEVRON_2 = 7,
	CHECKPOINT_RACE_GROUND_CHEVRON_3 = 8,
	CHECKPOINT_RACE_GROUND_LAP = 9,
	CHECKPOINT_RACE_GROUND_FLAG = 10,
	CHECKPOINT_RACE_GROUND_PIT_LANE = 11,
	CHECKPOINT_RACE_AIR_CHEVRON_1 = 12,
	CHECKPOINT_RACE_AIR_CHEVRON_2 = 13,
	CHECKPOINT_RACE_AIR_CHEVRON_3 = 14,
	CHECKPOINT_RACE_AIR_LAP = 15,
	CHECKPOINT_RACE_AIR_FLAG = 16,
	CHECKPOINT_RACE_WATER_CHEVRON_1 = 17,
	CHECKPOINT_RACE_WATER_CHEVRON_2 = 18,
	CHECKPOINT_RACE_WATER_CHEVRON_3 = 19,
	CHECKPOINT_RACE_WATER_LAP = 20,
	CHECKPOINT_RACE_WATER_FLAG = 21,
	CHECKPOINT_RACE_TRI_RUN_CHEVRON_1 = 22,
	CHECKPOINT_RACE_TRI_RUN_CHEVRON_2 = 23,
	CHECKPOINT_RACE_TRI_RUN_CHEVRON_3 = 24,
	CHECKPOINT_RACE_TRI_RUN_LAP = 25,
	CHECKPOINT_RACE_TRI_RUN_FLAG = 26,
	CHECKPOINT_RACE_TRI_SWIM_CHEVRON_1 = 27,
	CHECKPOINT_RACE_TRI_SWIM_CHEVRON_2 = 28,
	CHECKPOINT_RACE_TRI_SWIM_CHEVRON_3 = 29,
	CHECKPOINT_RACE_TRI_SWIM_LAP = 30,
	CHECKPOINT_RACE_TRI_SWIM_FLAG = 31,
	CHECKPOINT_RACE_TRI_CYCLE_CHEVRON_1 = 32,
	CHECKPOINT_RACE_TRI_CYCLE_CHEVRON_2 = 33,
	CHECKPOINT_RACE_TRI_CYCLE_CHEVRON_3 = 34,
	CHECKPOINT_RACE_TRI_CYCLE_LAP = 35,
	CHECKPOINT_RACE_TRI_CYCLE_FLAG = 36,
	CHECKPOINT_PLANE_FLAT = 37,
	CHECKPOINT_PLANE_SIDE_L = 38,
	CHECKPOINT_PLANE_SIDE_R = 39,
	CHECKPOINT_PLANE_INVERTED = 40,
	CHECKPOINT_HELI_LANDING = 41,
	CHECKPOINT_PARACHUTE_RING = 42,
	CHECKPOINT_PARACHUTE_LANDING = 43,
	CHECKPOINT_GANG_LOCATE_LOST = 44,
	CHECKPOINT_GANG_LOCATE_VAGOS = 45,
	CHECKPOINT_GANG_LOCATE_COPS = 46,
	CHECKPOINT_RACE_LOCATE_GROUND = 47,
	CHECKPOINT_RACE_LOCATE_AIR = 48,
	CHECKPOINT_RACE_LOCATE_WATER = 49,
	CHECKPOINT_MP_LOCATE_1 = 50,
	CHECKPOINT_MP_LOCATE_2 = 51,
	CHECKPOINT_MP_LOCATE_3 = 52,
	CHECKPOINT_MP_CREATOR_TRIGGER = 53,
	CHECKPOINT_MONEY = 54,
	CHECKPOINT_BEAST = 55,
	CHECKPOINT_TRANSFORM = 56,
	CHECKPOINT_TRANSFORM_PLANE = 57,
	CHECKPOINT_TRANSFORM_HELICOPTER = 58,
	CHECKPOINT_TRANSFORM_BOAT = 59,
	CHECKPOINT_TRANSFORM_CAR = 60,
	CHECKPOINT_TRANSFORM_BIKE = 61,
	CHECKPOINT_TRANSFORM_PUSH_BIKE = 62,
	CHECKPOINT_TRANSFORM_TRUCK = 63,
	CHECKPOINT_TRANSFORM_PARACHUTE = 64,
	CHECKPOINT_TRANSFORM_THRUSTER = 65,
	CHECKPOINT_WARP = 66,
}

---@class GFX_DRAW_ORDER
GFX_DRAW_ORDER = {
	GFX_ORDER_BEFORE_HUD_PRIORITY_LOW = 0,
	GFX_ORDER_BEFORE_HUD = 1, -- standard
	GFX_ORDER_BEFORE_HUD_PRIORITY_HIGH = 2,
	GFX_ORDER_AFTER_HUD_PRIORITY_LOW = 3,
	GFX_ORDER_AFTER_HUD = 4, -- standard
	GFX_ORDER_AFTER_HUD_PRIORITY_HIGH = 5,
	GFX_ORDER_AFTER_FADE_PRIORITY_LOW = 6,
	GFX_ORDER_AFTER_FADE = 7, -- standard
	GFX_ORDER_AFTER_FADE_PRIORITY_HIGH = 8,
}

---@class MARKER_TYPE
MARKER_TYPE = {
	MARKER_CONE = 0,
	MARKER_CYLINDER = 1,
	MARKER_ARROW = 2,
	MARKER_ARROW_FLAT = 3,
	MARKER_FLAG = 4,
	MARKER_RING_FLAG = 5,
	MARKER_RING = 6,
	MARKER_PLANE = 7,
	MARKER_BIKE_LOGO_1 = 8,
	MARKER_BIKE_LOGO_2 = 9,
	MARKER_NUM_0 = 10,
	MARKER_NUM_1 = 11,
	MARKER_NUM_2 = 12,
	MARKER_NUM_3 = 13,
	MARKER_NUM_4 = 14,
	MARKER_NUM_5 = 15,
	MARKER_NUM_6 = 16,
	MARKER_NUM_7 = 17,
	MARKER_NUM_8 = 18,
	MARKER_NUM_9 = 19,
	MARKER_CHEVRON_1 = 20,
	MARKER_CHEVRON_2 = 21,
	MARKER_CHEVRON_3 = 22,
	MARKER_RING_FLAT = 23,
	MARKER_LAP = 24,
	MARKER_HALO = 25,
	MARKER_HALO_POINT = 26,
	MARKER_HALO_ROTATE = 27,
	MARKER_SPHERE = 28,
	MARKER_MONEY = 29,
	MARKER_LINES = 30,
	MARKER_BEAST = 31,
	MARKER_QUESTION_MARK = 32,
	MARKER_TRANSFORM_PLANE = 33,
	MARKER_TRANSFORM_HELICOPTER = 34,
	MARKER_TRANSFORM_BOAT = 35,
	MARKER_TRANSFORM_CAR = 36,
	MARKER_TRANSFORM_BIKE = 37,
	MARKER_TRANSFORM_PUSH_BIKE = 38,
	MARKER_TRANSFORM_TRUCK = 39,
	MARKER_TRANSFORM_PARACHUTE = 40,
	MARKER_TRANSFORM_THRUSTER = 41,
	MARKER_WARP = 42,
	MARKER_BOXES = 43,
	MARKER_PIT_LANE = 44,
}

---@class DECAL_RENDERSETTING_ID
DECAL_RENDERSETTING_ID = {
	DECAL_RSID_BLOOD_SPLATTER = 1110,
	DECAL_RSID_BLOOD_DIRECTIONAL = 1015,
	DECAL_RSID_FOOTPRINT_SAND = 2020,
	DECAL_RSID_BULLET_IMPACT_METAL_SHOTGUN = 4202,
	DECAL_RSID_GENERIC_SCORCH = 4421,
	DECAL_RSID_FLOOR_SCUFF_1 = 7800,
	DECAL_RSID_FLOOR_SCUFF_2 = 7801,
	DECAL_RSID_FLOOR_SCUFF_3 = 7802,
	DECAL_RSID_FLOOR_SCUFF_4 = 7803,
	DECAL_RSID_LOGO_LOST_HOLLOW = 9100,
	DECAL_RSID_LOGO_LOST_GREY = 9101,
	DECAL_RSID_LOGO_LOST_WHITE = 9102,
	DECAL_RSID_LOGO_COPS_WHITE = 9103,
	DECAL_RSID_LOGO_VAGOS_WHITE = 9104,
	DECAL_RSID_RACE_LOCATE_GROUND = 9106,
	DECAL_RSID_RACE_LOCATE_AIR = 9107,
	DECAL_RSID_RACE_LOCATE_WATER = 9108,
	DECAL_RSID_TRIATHLON_CYCLING = 9110,
	DECAL_RSID_TRIATHLON_RUNNING = 9111,
	DECAL_RSID_TRIATHLON_SWIMMING = 9112,
	DECAL_RSID_HELIPAD = 9115,
	DECAL_RSID_PARACHUTE_LANDING = 9116,
	DECAL_RSID_SHADOW = 9117,
	DECAL_RSID_HALO = 9118,
	DECAL_RSID_HALO_PT = 9119,
	DECAL_RSID_MP_LOCATE_1 = 9120,
	DECAL_RSID_MP_LOCATE_2 = 9121,
	DECAL_RSID_MP_LOCATE_3 = 9122,
	DECAL_RSID_MP_CREATOR_TRIGGER = 9123,
	DECAL_RSID_OIL_POOL = 9200,
}

---@class THERMALBEHAVIOUR
THERMALBEHAVIOUR = {
	TB_DEAD = 0,
	TB_COLD = 1, -- Most animals
	TB_WARM = 2,
	TB_HOT = 3, -- Peds
}

---@class MOVIEMESHSETSTATE
MOVIEMESHSETSTATE = {
	MMS_FAILED = -1,
	MMS_PENDING_LOAD = 0,
	MMS_LOADED = 1,
	MMS_READY = 2,
	MMS_PENDING_DELETE = 3,
}

---@class TVCHANNELTYPE
TVCHANNELTYPE = {
	TVCHANNELTYPE_CHANNEL_NONE = -1,
	TVCHANNELTYPE_CHANNEL_1 = 0,
	TVCHANNELTYPE_CHANNEL_2 = 1,
	TVCHANNELTYPE_CHANNEL_SPECIAL = 2,
	TVCHANNELTYPE_CHANNEL_SCRIPT = 3, -- ONLY FOR USE IN LESTER1. If you don't know why you want to use this channel, you don't want to use this channel.
	TVCHANNELTYPE_CHANNEL_3 = 4, -- Requested for use in arcades in mpHeist3
}

---@class CREWEMBLEMREQUESTSTATE
CREWEMBLEMREQUESTSTATE = {
	CERS_NOT_ACTIVE = 0,
	CERS_REQUESTING_BADGE = 1,
	CERS_APPLYING_DECAL = 2,
	CERS_SUCCEEDED = 3,
	CERS_FAILED = 4,
	CERS_FAILED_CANT_GET_CLAN_TEXTURE = 5,
	CERS_FAILED_CANT_ADD_DATA_SLOT = 6,
	CERS_FAILED_VEHICLE_NO_LONGER_VALID = 7,
	CERS_FAILED_VEHICLE_BONE_NOT_VALID = 8,
	CERS_FAILED_VEHICLE_BONE_IS_ZERO = 9,
	CERS_FAILED_VEHICLE_PROBE_FAILED = 10,
	CERS_FAILED_DECAL_DIDNT_APPLY = 11,
}

---@class ANIMPOSTFX_EVENT_TYPE
ANIMPOSTFX_EVENT_TYPE = {
	ANIMPOSTFX_EVENT_INVALID = -1,
	ANIMPOSTFX_EVENT_ON_START = 0,
	ANIMPOSTFX_EVENT_ON_STOP = 1,
	ANIMPOSTFX_EVENT_ON_FRAME = 2,
}

---@class UI_ALIGNMENT
UI_ALIGNMENT = {
	UI_ALIGN_LEFT = 76, -- 'L'
	UI_ALIGN_RIGHT = 82, -- 'R'
	UI_ALIGN_TOP = 84, -- 'T'
	UI_ALIGN_BOTTOM = 66, -- 'B'
	UI_ALIGN_IGNORE = 73, -- 'I'
}

---@class PHOTO_OPERATION_STATUS
PHOTO_OPERATION_STATUS = {
	PHOTO_OPERATION_SUCCEEDED = 0,
	PHOTO_OPERATION_IN_PROGRESS = 1,
	PHOTO_OPERATION_FAILED = 2,
}

---@class eLowQualityPhotoSetting
eLowQualityPhotoSetting = {
	LOW_QUALITY_PHOTO_ONE = 0,
	LOW_QUALITY_PHOTO_HALF = 1,
	LOW_QUALITY_PHOTO_QUARTER = 2,
	LOW_QUALITY_PHOTO_EIGHTH = 3,
}

---@class ePhotoRotation
ePhotoRotation = {
	PHOTO_NO_ROTATION = 0,
	PHOTO_CLOCKWISE = 1,
	PHOTO_ANTI_CLOCKWISE = 2,
	PHOTO_MAX_ROTATIONS = 3,
}

