--- flags to specify what assets are required for a new stream volume
---@class STREAMVOL_ASSET_TYPES
STREAMVOL_ASSET_TYPES = {
	FLAG_COLLISIONS_MOVER = 1,
	FLAG_COLLISIONS_WEAPON = 2,
	FLAG_MAPDATA = 12,
}

---@class STREAMVOL_LOD_FLAGS
STREAMVOL_LOD_FLAGS = {
	STREAMVOL_LOD_FLAG_HIGH = 33, -- 0b00100001
	STREAMVOL_LOD_FLAG_LOW = 94, -- 0b01011110
	STREAMVOL_LOD_FLAG_ALL = 127, -- 0b01111111
}

---@class NEWLOADSCENE_FLAGS
NEWLOADSCENE_FLAGS = {
	NEWLOADSCENE_FLAG_REQUIRE_COLLISION = 1,
	NEWLOADSCENE_FLAG_LONGSWITCH_CUTSCENE = 2,
	NEWLOADSCENE_FLAG_INTERIOR_AND_EXTERIOR = 4,
}

--- control flags for player switching
---@class SWITCH_FLAGS
SWITCH_FLAGS = {
	SWITCH_FLAG_SKIP_INTRO = 1,
	SWITCH_FLAG_SKIP_OUTRO = 2,
	SWITCH_FLAG_PAUSE_BEFORE_PAN = 4,
	SWITCH_FLAG_PAUSE_BEFORE_OUTRO = 8,
	SWITCH_FLAG_SKIP_PAN = 16,
	SWITCH_FLAG_UNKNOWN_DEST = 32,
	SWITCH_FLAG_DESCENT_ONLY = 64,
	SWITCH_FLAG_START_FROM_CAMPOS = 128,
	SWITCH_FLAG_PAUSE_BEFORE_ASCENT = 256,
	SWITCH_FLAG_PAUSE_BEFORE_DESCENT = 512,
	SWITCH_FLAG_ALLOW_SNIPER_AIM_INTRO = 1024,
	SWITCH_FLAG_ALLOW_SNIPER_AIM_OUTRO = 2048,
	SWITCH_FLAG_SKIP_TOP_DESCENT = 4096,
	SWITCH_FLAG_SUPPRESS_OUTRO_FX = 8192,
	SWITCH_FLAG_SUPPRESS_INTRO_FX = 16384,
	SWITCH_FLAG_DELAY_ASCENT_FX = 32768,
}

--- List of states the player switch manager can be in. Must match up
--- with eState in CPlayerSwitchMgrLong
--- TODO: Remove SWITCH_STATE_OUTRO once the script reference has been changed to (>=) SWITCH_STATE_OUTRO_HOLD
---@class SWITCH_STATE
SWITCH_STATE = {
	SWITCH_STATE_INTRO = 0,
	SWITCH_STATE_PREP_DESCENT = 1,
	SWITCH_STATE_PREP_FOR_CUT = 2,
	SWITCH_STATE_JUMPCUT_ASCENT = 3,
	SWITCH_STATE_WAITFORINPUT_INTRO = 4,
	SWITCH_STATE_WAITFORINPUT = 5,
	SWITCH_STATE_WAITFORINPUT_OUTRO = 6,
	SWITCH_STATE_PAN = 7,
	SWITCH_STATE_JUMPCUT_DESCENT = 8,
	SWITCH_STATE_OUTRO_HOLD = 9,
	SWITCH_STATE_OUTRO_SWOOP = 10,
	SWITCH_STATE_ESTABLISHING_SHOT = 11,
	SWITCH_STATE_FINISHED = 12,
	SWITCH_STATE_OUTRO = SWITCH_STATE_OUTRO_HOLD,
}

--- List of states the short-range player switch manager can be in. Must match up
--- with eState in CPlayerSwitchMgrShort
---@class SHORT_SWITCH_STATE
SHORT_SWITCH_STATE = {
	SHORT_SWITCH_STATE_INTRO = 0,
	SHORT_SWITCH_STATE_OUTRO = 1,
}

--- List of styles the short-range player switch manager can use.
--- Must match up with eStyle in CPlayerSwitchMgrShort
---@class SHORT_SWITCH_STYLE
SHORT_SWITCH_STYLE = {
	SHORT_SWITCH_STYLE_ROTATION = 0,
	SHORT_SWITCH_STYLE_TRANSLATION = 1,
	SHORT_SWITCH_STYLE_ZOOM_TO_HEAD = 2,
	SHORT_SWITCH_STYLE_ZOOM_IN_OUT = 3,
}

--- List of switch types currently supported. The default (auto) just automatically
--- selects the most appropriate switch type based on the distance between two peds.
---@class SWITCH_TYPE
SWITCH_TYPE = {
	SWITCH_TYPE_AUTO = 0,
	SWITCH_TYPE_LONG = 1,
	SWITCH_TYPE_MEDIUM = 2,
	SWITCH_TYPE_SHORT = 3,
}

---@class SRL_PRESTREAM_MODE
SRL_PRESTREAM_MODE = {
	SRL_PRESTREAM_DEFAULT = 0,
	SRL_PRESTREAM_FORCE_ON = 1, -- 1
	SRL_PRESTREAM_FORCE_OFF = 2, -- 2
	SRL_PRESTREAM_FORCE_COMPLETELY_OFF = 3, -- 3
}

