---@class ROMANS_MOOD
ROMANS_MOOD = {
	ROMANS_MOOD_NORMAL = 0,
	ROMANS_MOOD_SAD = 1, -- 1
	ROMANS_MOOD_SHAKEN_UP = 2, -- 2
	ROMANS_MOOD_DRUNK = 3, -- 3
}

---@class BRIANS_MOOD
BRIANS_MOOD = {
	BRIANS_MOOD_CLEAN = 0,
	BRIANS_MOOD_DRUG = 1, -- 1
}

---@class AUD_ANIMAL_MOOD
AUD_ANIMAL_MOOD = {
	AUD_ANIMAL_MOOD_ANGRY = 0,
	AUD_ANIMAL_MOOD_PLAYFUL = 1,
	AUD_ANIMAL_MOOD_NUM_MOODS = 2,
}

---@class AUD_CONTEXT_BLOCK_TARGET
AUD_CONTEXT_BLOCK_TARGET = {
	AUD_CONTEXT_BLOCK_PLAYER = 0,
	AUD_CONTEXT_BLOCK_NPCS = 1,
	AUD_CONTEXT_BLOCK_BUDDYS = 2,
	AUD_CONTEXT_BLOCK_EVERYONE = 3,
	AUD_CONTEXT_BLOCK_TARGETS_TOTAL = 4,
}

--- Must match the enum in speechAudioEntity
---@class SPEECH_PARAMS
SPEECH_PARAMS = {
	SPEECH_PARAMS_STANDARD = 0,
	SPEECH_PARAMS_ALLOW_REPEAT = 1,
	SPEECH_PARAMS_BEAT = 2,
	SPEECH_PARAMS_FORCE = 3,
	SPEECH_PARAMS_FORCE_FRONTEND = 4,
	SPEECH_PARAMS_FORCE_NO_REPEAT_FRONTEND = 5,
	SPEECH_PARAMS_FORCE_NORMAL = 6,
	SPEECH_PARAMS_FORCE_NORMAL_CLEAR = 7,
	SPEECH_PARAMS_FORCE_NORMAL_CRITICAL = 8,
	SPEECH_PARAMS_FORCE_SHOUTED = 9,
	SPEECH_PARAMS_FORCE_SHOUTED_CLEAR = 10,
	SPEECH_PARAMS_FORCE_SHOUTED_CRITICAL = 11,
	SPEECH_PARAMS_FORCE_PRELOAD_ONLY = 12,
	SPEECH_PARAMS_MEGAPHONE = 13,
	SPEECH_PARAMS_HELI = 14,
	SPEECH_PARAMS_FORCE_MEGAPHONE = 15,
	SPEECH_PARAMS_FORCE_HELI = 16,
	SPEECH_PARAMS_INTERRUPT = 17,
	SPEECH_PARAMS_INTERRUPT_SHOUTED = 18,
	SPEECH_PARAMS_INTERRUPT_SHOUTED_CLEAR = 19,
	SPEECH_PARAMS_INTERRUPT_SHOUTED_CRITICAL = 20,
	SPEECH_PARAMS_INTERRUPT_NO_FORCE = 21,
	SPEECH_PARAMS_INTERRUPT_FRONTEND = 22,
	SPEECH_PARAMS_INTERRUPT_NO_FORCE_FRONTEND = 23,
	SPEECH_PARAMS_ADD_BLIP = 24,
	SPEECH_PARAMS_ADD_BLIP_ALLOW_REPEAT = 25,
	SPEECH_PARAMS_ADD_BLIP_FORCE = 26,
	SPEECH_PARAMS_ADD_BLIP_SHOUTED = 27,
	SPEECH_PARAMS_ADD_BLIP_SHOUTED_FORCE = 28,
	SPEECH_PARAMS_ADD_BLIP_INTERRUPT = 29,
	SPEECH_PARAMS_ADD_BLIP_INTERRUPT_FORCE = 30,
	SPEECH_PARAMS_FORCE_PRELOAD_ONLY_SHOUTED = 31,
	SPEECH_PARAMS_FORCE_PRELOAD_ONLY_SHOUTED_CLEAR = 32,
	SPEECH_PARAMS_FORCE_PRELOAD_ONLY_SHOUTED_CRITICAL = 33,
	SPEECH_PARAMS_SHOUTED = 34,
	SPEECH_PARAMS_SHOUTED_CLEAR = 35,
	SPEECH_PARAMS_SHOUTED_CRITICAL = 36,
}

---@class POLICE_SCANNER_CAR_CODE
POLICE_SCANNER_CAR_CODE = {
	CAR_CODE_A = 0,
	CAR_CODE_B = 1,
	CAR_CODE_C = 2,
	CAR_CODE_D = 3,
	CAR_CODE_E = 4,
	CAR_CODE_F = 5,
	CAR_CODE_G = 6,
	CAR_CODE_H = 7,
	CAR_CODE_I = 8,
	CAR_CODE_J = 9,
	CAR_CODE_K = 10,
	CAR_CODE_L = 11,
	CAR_CODE_M = 12,
	CAR_CODE_N = 13,
	CAR_CODE_O = 14,
	CAR_CODE_P = 15,
	CAR_CODE_Q = 16,
	CAR_CODE_R = 17,
	CAR_CODE_S = 18,
	CAR_CODE_T = 19,
	CAR_CODE_U = 20,
	CAR_CODE_V = 21,
	CAR_CODE_W = 22,
	CAR_CODE_X = 23,
	CAR_CODE_Y = 24,
	CAR_CODE_Z = 25,
}

--- This will probably be removed once we have a code-side method for determining animal type
---@class AUD_ANIMAL_TYPE
AUD_ANIMAL_TYPE = {
	AUD_ANIMAL_NONE = -1,
	AUD_ANIMAL_BOAR = 0,
	AUD_ANIMAL_CHICKEN = 1,
	AUD_ANIMAL_DOG = 2,
	AUD_ANIMAL_DOG_ROTTWEILER = 3,
	AUD_ANIMAL_HORSE = 4,
	AUD_NUM_ANIMALS = 5,
}

--- Should match the audDamageReason enum
---@class AUD_DAMAGE_REASON
AUD_DAMAGE_REASON = {
	AUD_DAMAGE_REASON_DEFAULT = 0,
	AUD_DAMAGE_REASON_FALLING = 1,
	AUD_DAMAGE_REASON_SUPER_FALLING = 2,
	AUD_DAMAGE_REASON_SCREAM_PANIC = 3,
	AUD_DAMAGE_REASON_SCREAM_PANIC_SHORT = 4,
	AUD_DAMAGE_REASON_SCREAM_SCARED = 5,
	AUD_DAMAGE_REASON_SCREAM_SHOCKED = 6,
	AUD_DAMAGE_REASON_SCREAM_TERROR = 7,
	AUD_DAMAGE_REASON_ON_FIRE = 8,
	AUD_DAMAGE_REASON_DROWNING = 9,
	AUD_DAMAGE_REASON_SURFACE_DROWNING = 10, -- drowning on the surface of water, after we time out
	AUD_DAMAGE_REASON_INHALE = 11,
	AUD_DAMAGE_REASON_EXHALE = 12,
	AUD_DAMAGE_REASON_POST_FALL_GRUNT = 13,
	AUD_DAMAGE_REASON_ENTERING_RAGDOLL_DEATH = 14,
	AUD_DAMAGE_REASON_EXPLOSION = 15,
	AUD_DAMAGE_REASON_MELEE = 16,
	AUD_DAMAGE_REASON_SHOVE = 17,
	AUD_DAMAGE_REASON_WHEEZE = 18,
	AUD_DAMAGE_REASON_COUGH = 19,
	AUD_DAMAGE_REASON_TAZER = 20,
	AUD_DAMAGE_REASON_EXHAUSTION = 21,
	AUD_DAMAGE_REASON_CLIMB_LARGE = 22,
	AUD_DAMAGE_REASON_CLIMB_SMALL = 23,
	AUD_DAMAGE_REASON_JUMP = 24,
	AUD_DAMAGE_REASON_COWER = 25,
	AUD_DAMAGE_REASON_WHIMPER = 26,
	AUD_DAMAGE_REASON_DYING_MOAN = 27,
	AUD_DAMAGE_REASON_CYCLING_EXHALE = 28,
	AUD_DAMAGE_REASON_PAIN_RAPIDS = 29,
	AUD_DAMAGE_REASON_SNEEZE = 30,
	AUD_DAMAGE_REASON_MELEE_SMALL_GRUNT = 31,
	AUD_DAMAGE_REASON_MELEE_LARGE_GRUNT = 32,
	AUD_DAMAGE_REASON_POST_FALL_GRUNT_LOW = 33,
}

---@class eAUDIBILITY
eAUDIBILITY = {
	AUD_AUDIBILITY_NORMAL = 0,
	AUD_AUDIBILITY_CLEAR = 1,
	AUD_AUDIBILITY_CRITICAL = 2,
	AUD_AUDIBILITY_LEAD_IN = 3,
}

---@class AUD_AIRCRAFT_WARNING_TYPES
AUD_AIRCRAFT_WARNING_TYPES = {
	AUD_AW_TARGETED_LOCK = 0,
	AUD_AW_MISSLE_FIRED = 1,
	AUD_AW_ACQUIRING_TARGET = 2,
	AUD_AW_TARGET_ACQUIRED = 3,
	AUD_AW_ALL_CLEAR = 4,
	AUD_AW_PLANE_WARNING_STALL = 5,
	AUD_AW_ALTITUDE_WARNING_LOW = 6,
	AUD_AW_ALTITUDE_WARNING_HIGH = 7,
	AUD_AW_ENGINE_1_FIRE = 8,
	AUD_AW_ENGINE_2_FIRE = 9,
	AUD_AW_ENGINE_3_FIRE = 10,
	AUD_AW_ENGINE_4_FIRE = 11,
	AUD_AW_DAMAGED_SERIOUS = 12,
	AUD_AW_DAMAGED_CRITICAL = 13,
	AUD_AW_OVERSPEED = 14,
	AUD_AW_TERRAIN = 15,
	AUD_AW_PULL_UP = 16,
	AUD_AW_LOW_FUEL = 17,
	AUD_AW_NUM_WARNINGS = 18,
}

--- Must match the enum in AudioDefinitions.xml
---@class RADIO_GENRE
RADIO_GENRE = {
	RADIO_GENRE_OFF = 0,
	RADIO_GENRE_MODERN_ROCK = 1,
	RADIO_GENRE_CLASSIC_ROCK = 2,
	RADIO_GENRE_POP = 3,
	RADIO_GENRE_MODERN_HIPHOP = 4,
	RADIO_GENRE_CLASSIC_HIPHOP = 5,
	RADIO_GENRE_PUNK = 6,
	RADIO_GENRE_LEFT_WING_TALK = 7,
	RADIO_GENRE_RIGHT_WING_TALK = 8,
	RADIO_GENRE_COUNTRY = 9,
	RADIO_GENRE_DANCE = 10,
	RADIO_GENRE_MEXICAN = 11,
	RADIO_GENRE_REGGAE = 12,
	RADIO_GENRE_JAZZ = 13,
	RADIO_GENRE_MOTOWN = 14,
	RADIO_GENRE_SURF = 15,
	RADIO_GENRE_UNSPECIFIED = 16,
}

---@class AUDIO_VEHICLE_PRIORITY
AUDIO_VEHICLE_PRIORITY = {
	AUDIO_VEHICLE_PRIORITY_NORMAL = 0,
	AUDIO_VEHICLE_PRIORITY_MEDIUM = 1,
	AUDIO_VEHICLE_PRIORITY_HIGH = 2,
	AUDIO_VEHICLE_PRIORITY_MAX = 3,
}

---@class AUDIO_SPECIAL_EFFECT_MODE
AUDIO_SPECIAL_EFFECT_MODE = {
	AUDIO_SPECIAL_EFFECT_MODE_NORMAL = 0,
	AUDIO_SPECIAL_EFFECT_MODE_UNDERWATER = 1,
	AUDIO_SPECIAL_EFFECT_MODE_STONED = 2,
}

