---@class GANGS
GANGS = {
	GANG_ALBANIAN = 0, -- 0
	GANG_BIKER_1 = 1, -- 1
	GANG_BIKER_2 = 2, -- 2
	GANG_ITALIAN = 3, -- 3
	GANG_RUSSIAN = 4, -- 4
	GANG_RUSSIAN_2 = 5, -- 5
	GANG_IRISH = 6, -- 6
	GANG_JAMAICAN = 7, -- 7
	GANG_AFRICAN_AMERICAN = 8, -- 8
	GANG_KOREAN = 9, -- 9
	GANG_CHINESE_JAPANESE = 10, -- 10
	GANG_PUERTO_RICAN = 11, -- 11
}

