---@class WEATHER_TYPE
WEATHER_TYPE = {
	WEATHER_EXTRASUNNY = 0,
	WEATHER_CLEAR = 1,
	WEATHER_CLOUDS = 2,
	WEATHER_SMOG = 3,
	WEATHER_CLOUDY = 4,
	WEATHER_OVERCAST = 5,
	WEATHER_RAIN = 6,
	WEATHER_THUNDER = 7,
	WEATHER_CLEARING = 8,
	WEATHER_NEUTRAL = 9,
	WEATHER_SNOWLIGHT = 10,
	WEATHER_SNOW = 11,
	WEATHER_BLIZZARD = 12,
}

---@class eHUD_PHONE_ITEM
eHUD_PHONE_ITEM = {
	HUD_PHONE_ITEM_NONE = 0,
	HUD_PHONE_ITEM_TEXT_MESSAGE = 1,
	HUD_PHONE_ITEM_CONTACT = 2,
	HUD_PHONE_ITEM_MEETING = 3,
	HUD_PHONE_ITEM_APPOINTMENT = 4,
	HUD_PHONE_ITEM_REPLAY = 5,
	HUD_PHONE_ITEM_PICTURE_MESSAGE = 6,
	HUD_PHONE_ITEM_DISCONNECT = 7,
	HUD_PHONE_ITEM_FRIEND_INC = 8,
	HUD_PHONE_ITEM_FRIEND_DEC = 9,
	HUD_PHONE_ITEM_INVITE = 10,
}

---@class CHEAT_TYPE
CHEAT_TYPE = {
	POOR_WEAPON_CHEAT = 0,
	ADVANCED_WEAPON_CHEAT = 1,
	HEALTH_CHEAT = 2,
	WANTED_LEVEL_UP_CHEAT = 3,
	WANTED_LEVEL_DOWN_CHEAT = 4,
	MONEY_UP_CHEAT = 5,
	CHANGE_WEATHER_CHEAT = 6,
	ANNIHILATOR_CHEAT = 7,
	NRG900_CHEAT = 8,
	FBI_CHEAT = 9,
	JETMAX_CHEAT = 10,
	COMET_CHEAT = 11,
	TURISMO_CHEAT = 12,
	COGNOSCENTI_CHEAT = 13,
	SUPERGT_CHEAT = 14,
	SANCHEZ_CHEAT = 15,
}

---@class PROFILE_SETTING
PROFILE_SETTING = {
	PROFILE_ACTION_AUTO_AIM = 0,
	PROFILE_YAXIS_INVERSION = 1,
	PROFILE_CONTROLLER_VIBRATION = 2,
	PROFILE_CONTROLLER_SENSITIVITY = 3,
	PROFILE_CONTROLLER_SIXAXIS_HELI = 5,
	PROFILE_CONTROLLER_SIXAXIS_BIKE = 6,
	PROFILE_CONTROLLER_SIXAXIS_BOAT = 7,
	PROFILE_CONTROLLER_SIXAXIS_RELOAD = 8,
	PROFILE_CONTROLLER_SIXAXIS_MISSION = 9,
	PROFILE_CONTROLLER_SIXAXIS_ACTIVITY = 10,
	PROFILE_CONTROLLER_SIXAXIS_AFTERTOUCH = 11,
	PROFILE_CONTROLLER_CONTROL_CONFIG = 12,
	PROFILE_CONTROLLER_SNIPER_ZOOM = 17,
	PROFILE_VOICE_THRU_SPEAKERS = 100,
	PROFILE_VOICE_MUTED = 101,
	PROFILE_VOICE_VOLUME = 102,
	PROFILE_DISPLAY_SUBTITLES = 203,
	PROFILE_DISPLAY_RADAR_MODE = 204,
	PROFILE_DISPLAY_HUD_MODE = 205,
	PROFILE_DISPLAY_LANGUAGE = 206,
	PROFILE_DISPLAY_GPS = 207,
	PROFILE_DISPLAY_AUTOSAVE_MODE = 208,
	PROFILE_DISPLAY_HANDBRAKE_CAM = 209,
	PROFILE_CONTROLLER_CINEMATIC_SHOOTING = 211,
	PROFILE_DISPLAY_SAFEZONE_SIZE = 212,
	PROFILE_DISPLAY_GAMMA = 213,
	PROFILE_DISPLAY_CAMERA_HEIGHT = 220,
	PROFILE_DIAPLAY_BIG_RADAR = 221,
	PROFILE_DIAPLAY_BIG_RADAR_NAMES = 222,
	PROFILE_AUDIO_SFX_LEVEL = 300,
	PROFILE_AUDIO_MUSIC_LEVEL = 301,
	PROFILE_AUDIO_VOICE_OUTPUT = 302,
	PROFILE_AUDIO_GPS_SPEECH = 303,
	PROFILE_AUDIO_HIGH_DYNAMIC_RANGE = 304,
	PROFILE_AUDIO_SPEAKER_OUTPUT = 305,
	PROFILE_AUDIO_MUSIC_LEVEL_IN_MP = 306,
	PROFILE_AUDIO_INTERACTIVE_MUSIC = 307,
	PROFILE_AUDIO_DIALOGUE_BOOST = 308,
	PROFILE_AUDIO_VOICE_SPEAKER = 309,
	SAVE_MIGRATION_TRANSACTION_ID_WARNING = 501,
	SAVE_MIGRATION_TRANSACTION_ID = 502,
	PROFILE_FEED_PHONE = 800,
	PROFILE_FEED_STATS = 801,
	PROFILE_FEED_CREW = 802,
	PROFILE_FEED_FRIENDS = 803,
	PROFILE_FEED_SOCIAL = 804,
	PROFILE_FEED_STORE = 805,
	PROFILE_FEED_TOOLTIP = 806,
	PROFILE_FEED_DELAY = 807,
	TICKER_JOHN_MARSTON_IS_AVAILABLE = 850,
	GAMER_PLAYED_LAST_GEN = 865, -- Indicates if the player has played last gen, 1 - 360, 3 - ps3.
	GAMER_HAS_SPECIALEDITION_CONTENT = 866, -- Indicates if the player is entitled to special edition content
	PROFILE_FACEBOOK_UPDATES = 900,
	ROS_WENT_DOWN_NOT_NET = 901,
	FACEBOOK_POSTED_BOUGHT_GAME = 902,
	PROLOGUE_COMPLETE = 903,
	FACEBOOK_POSTED_ALL_VEHICLES_DRIVEN = 904,
	EULA_VERSION = 905,
	TOS_VERSION = 907,
	PRIVACY_VERSION = 908,
	JOB_ACTIVITY_ID_CHAR0 = 909, -- Id of the UGC activity started so we know if the player has pulled the plug.
	JOB_ACTIVITY_ID_CHAR1 = 910, -- Id of the UGC activity started so we know if the player has pulled the plug.
	JOB_ACTIVITY_ID_CHAR2 = 911, -- Id of the UGC activity started so we know if the player has pulled the plug.
	JOB_ACTIVITY_ID_CHAR3 = 912, -- Id of the UGC activity started so we know if the player has pulled the plug.
	JOB_ACTIVITY_ID_CHAR4 = 913, -- Id of the UGC activity started so we know if the player has pulled the plug.
	FREEMODE_PROLOGUE_COMPLETE_CHAR0 = 914, -- Returns a value !=0 if the prologue was done.
	FREEMODE_PROLOGUE_COMPLETE_CHAR1 = 915, -- Returns a value !=0 if the prologue was done.
	FREEMODE_PROLOGUE_COMPLETE_CHAR2 = 916, -- Returns a value !=0 if the prologue was done.
	FREEMODE_PROLOGUE_COMPLETE_CHAR3 = 917, -- Returns a value !=0 if the prologue was done.
	FREEMODE_PROLOGUE_COMPLETE_CHAR4 = 918, -- Returns a value !=0 if the prologue was done.
	MP_FLUSH_POSIXTIME_HIGH32 = 919, -- s64 value for the last mp successful profile stats flush.
	MP_FLUSH_POSIXTIME_LOW32 = 920,
	MP_CLOUD0_POSIXTIME_HIGH32 = 921, -- s64 value for the last mp successful cloud save.
	MP_CLOUD0_POSIXTIME_LOW32 = 922,
	MP_CLOUD1_POSIXTIME_HIGH32 = 923, -- s64 value for the last mp successful cloud save.
	MP_CLOUD1_POSIXTIME_LOW32 = 924,
	MP_CLOUD2_POSIXTIME_HIGH32 = 925, -- s64 value for the last mp successful cloud save.
	MP_CLOUD2_POSIXTIME_LOW32 = 926,
	MP_CLOUD3_POSIXTIME_HIGH32 = 927, -- s64 value for the last mp successful cloud save.
	MP_CLOUD3_POSIXTIME_LOW32 = 928,
	MP_CLOUD_POSIXTIME_HIGH32 = 931, -- s64 value for the last mp successful cloud save.
	MP_CLOUD_POSIXTIME_LOW32 = 932,
	MP_AWD_CREATOR_RACES_DONE = 933,
	MP_AWD_CREATOR_DM_DONE = 934,
	MP_AWD_CREATOR_CTF_DONE = 935,
	MP_CREATOR_RACES_SAVED = 936,
	MP_CREATOR_DM_SAVED = 937,
	MP_CREATOR_CTF_SAVED = 938,
	SP_CHOP_MISSION_COMPLETE = 939,
	FREEMODE_STRAND_PROGRESSION_STATUS_CHAR0 = 940,
	FREEMODE_STRAND_PROGRESSION_STATUS_CHAR1 = 941,
	MP_CAMERA_ZOOM_ON_FOOT = 950,
	MP_CAMERA_ZOOM_IN_VEHICLE = 951,
	MP_CAMERA_ZOOM_ON_BIKE = 952,
	MP_CAMERA_ZOOM_IN_BOAT = 953,
	MP_CAMERA_ZOOM_IN_AIRCRAFT = 954,
	MP_CAMERA_ZOOM_IN_HELI = 955,
}

---@class GRAVITY_LEVEL
GRAVITY_LEVEL = {
	GRAV_EARTH = 0,
	GRAV_MOON = 1,
	GRAV_LOW = 2,
	GRAV_ZERO = 3,
}

--- keep this in sync with enum in DispatchEnums.h
---@class DISPATCH_TYPE
DISPATCH_TYPE = {
	DT_POLICE_AUTOMOBILE = 1,
	DT_POLICE_HELICOPTER = 2,
	DT_FIRE_DEPARTMENT = 3,
	DT_SWAT_AUTOMOBILE = 4,
	DT_AMBULANCE_DEPARTMENT = 5,
	DT_POLICE_RIDERS = 6,
	DT_POLICE_VEHICLE_REQUEST = 7,
	DT_POLICE_ROAD_BLOCK = 8,
	DT_POLICE_AUTOMOBILE_WAIT_PULLED_OVER = 9,
	DT_POLICE_AUTOMOBILE_WAIT_CRUISING = 10,
	DT_GANGS = 11,
	DT_SWAT_HELICOPTER = 12,
	DT_POLICE_BOAT = 13,
	DT_ARMY_VEHICLE = 14,
	DT_BIKER_BACKUP = 15,
	DT_ASSASSINS = 16,
}

--- keep this in sync with enum in DispatchEnums.h
---@class ASSASSIN_LEVEL
ASSASSIN_LEVEL = {
	AL_LOW = 1,
	AL_MED = 2,
	AL_HIGH = 3,
}

--- Keep this in sync with the enum in virtualkeyboard.h
---@class OSK_STATUS
OSK_STATUS = {
	OSK_INVALID = -1,
	OSK_PENDING = 0,
	OSK_SUCCESS = 1,
	OSK_CANCELLED = 2,
	OSK_FAILED = 3,
}

---@class RANDOM_EVENT
RANDOM_EVENT = {
	RC_PED_STEAL_VEHICLE = 0,
	RC_PED_JAY_WALK_LIGHTS = 1,
	RC_COP_PURSUE = 2,
	RC_COP_PURSUE_VEHICLE_FLEE_SPAWNED = 3,
	RC_COP_VEHICLE_DRIVING_FAST = 4,
	RC_DRIVER_SLOW = 5,
	RC_DRIVER_RECKLESS = 6,
	RC_DRIVER_PRO = 7,
	RC_PED_PURSUE_WHEN_HIT_BY_CAR = 8,
}

---@class ELEMENT_LOC_BLOCK
ELEMENT_LOC_BLOCK = {
	ELEMENT_LOC_BLOCK_BASE = 0,
	ELEMENT_LOC_BLOCK_HI_APT = 1,
	ELEMENT_LOC_BLOCK_EXTRA_1 = 2,
	ELEMENT_LOC_BLOCK_EXTRA_2 = 3,
	ELEMENT_LOC_BLOCK_EXTRA_3 = 4,
	ELEMENT_LOC_BLOCK_EXTRA_4 = 5,
	ELEMENT_LOC_BLOCK_EXTRA_5 = 6,
	ELEMENT_LOC_BLOCK_EXTRA_6 = 7,
	ELEMENT_LOC_BLOCK_EXTRA_7 = 8,
	ELEMENT_LOC_BLOCK_EXTRA_8 = 9,
	ELEMENT_LOC_BLOCK_EXTRA_9 = 10,
	ELEMENT_LOC_BLOCK_EXTRA_10 = 11,
	ELEMENT_LOC_BLOCK_EXTRA_11 = 12,
	ELEMENT_LOC_BLOCK_EXTRA_12 = 13,
	ELEMENT_LOC_BLOCK_EXTRA_13 = 14,
	ELEMENT_LOC_BLOCK_EXTRA_14 = 15,
}

---@class CLEAROBJECTS_FLAGS
CLEAROBJECTS_FLAGS = {
	CLEAROBJ_FLAG_BROADCAST = 1,
	CLEAROBJ_FLAG_FORCE = 2,
	CLEAROBJ_FLAG_INCLUDE_DOORS = 4,
	CLEAROBJ_FLAG_INCLUDE_OBJWITHBRAINS = 8,
	CLEAROBJ_FLAG_EXCLUDE_LADDERS = 16,
}

--- ~>                    Save commands
---@class SAVEGAME_OPERATION_STATUS
SAVEGAME_OPERATION_STATUS = {
	SAVEGAME_OPERATION_SUCCEEDED = 0,
	SAVEGAME_OPERATION_IN_PROGRESS = 1,
	SAVEGAME_OPERATION_FAILED = 2,
}

---@class eLevelIndex
eLevelIndex = {
	LEVEL_GTA5 = 1,
	LEVEL_TESTBED = 2,
	LEVEL_VFX_TEST = 3,
	LEVEL_NM_TEST = 4,
	LEVEL_NET_TEST = 5,
	LEVEL_ANIM_TEST = 6,
	LEVEL_CP_TESTBED = 7,
	LEVEL_TOOLS_TEST = 8,
	LEVEL_WATERBED = 9,
	LEVEL_GFX_TEST = 10,
}

--- ******************************************************************************************
--- **** Cell Phone Camera commands (copied from command_ny.sch in GTA4) ****
--- ******************************************************************************************
---@class MOBILE_PHONE_TYPE
MOBILE_PHONE_TYPE = {
	MOBILE_1 = 0,
	MOBILE_2 = 1,
	MOBILE_3 = 2,
	MOBILE_4 = 3,
	MOBILE_5 = 4, -- Prologue Phone
}

--- ENSURE IN SYNC WITH ENUM ePhoneInput IN TASKMOBILEPHONE.H
---@class CELL_INPUT
CELL_INPUT = {
	CELL_INPUT_NONE = 0,
	CELL_INPUT_UP = 1,
	CELL_INPUT_DOWN = 2,
	CELL_INPUT_LEFT = 3,
	CELL_INPUT_RIGHT = 4,
	CELL_INPUT_SELECT = 5,
}

---@class TENNIS_DIVE_DIRECTION
TENNIS_DIVE_DIRECTION = {
	DIVE_BH = 0,
	DIVE_FH = 1,
}

---@class eKeyboardType
eKeyboardType = {
	ONSCREEN_KEYBOARD_ENGLISH = 0,
	ONSCREEN_KEYBOARD_LOCALISED = 1,
	ONSCREEN_KEYBOARD_PASSWORD = 2,
	ONSCREEN_KEYBOARD_GAMERTAG = 3,
	ONSCREEN_KEYBOARD_EMAIL = 4,
	ONSCREEN_KEYBOARD_BASIC_ENGLISH = 5,
	ONSCREEN_KEYBOARD_FILENAME = 6,
}

---@class FONT_BIT_FIELD
FONT_BIT_FIELD = {
	FONT_BIT_CURSIVE = 2,
	FONT_BIT_ROCKSTAR_TAG = 4,
	FONT_BIT_LEADERBOARD = 8,
	FONT_BIT_CONDENSED = 16,
	FONT_BIT_FIXED_WIDTH_NUMBERS = 32,
	FONT_BIT_CONDENSED_NOT_GAMERNAME = 64,
	FONT_BIT_PRICEDOWN = 128, -- gta font
}

---@class INSTANCE_MODE
INSTANCE_MODE = {
	INSTANCE_MODE_SINGLEPLAYER = 0,
	INSTANCE_MODE_MULTIPLAYER = 1,
}

---@class INSTANCE_HINT
INSTANCE_HINT = {
	INSTANCE_HINT_NONE = 0,
	INSTANCE_HINT_SHOOTING = 1,
	INSTANCE_HINT_DRIVING = 2,
	INSTANCE_HINT_SNIPING = 3,
	INSTANCE_HINT_HELICAM = 4,
}

