---@class LANGUAGE_TYPE
LANGUAGE_TYPE = {
	LANGUAGE_UNDEFINED = -1,
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_FRENCH = 1,
	LANGUAGE_GERMAN = 2,
	LANGUAGE_ITALIAN = 3,
	LANGUAGE_SPANISH = 4,
	LANGUAGE_PORTUGUESE = 5,
	LANGUAGE_POLISH = 6,
	LANGUAGE_RUSSIAN = 7,
	LANGUAGE_KOREAN = 8,
	LANGUAGE_CHINESE = 9,
	LANGUAGE_JAPANESE = 10,
	LANGUAGE_MEXICAN = 11,
	LANGUAGE_CHINESE_SIMPLIFIED = 12,
}

---@class DATE_FORMAT
DATE_FORMAT = {
	DATE_FORMAT_DMY = 0,
	DATE_FORMAT_MDY = 1,
	DATE_FORMAT_YMD = 2,
	MAX_DATE_FORMATS = 3,
}

---@class DATE_FORMAT_DELIMITER
DATE_FORMAT_DELIMITER = {
	DATE_FORMAT_DELIMITER_SLASH = 0,
	DATE_FORMAT_DELIMITER_DASH = 1,
	DATE_FORMAT_DELIMITER_DOT = 2,
	DATE_FORMAT_DELIMITER_SPACE = 3,
	MAX_DATE_FORMAT_DELIMITERS = 4,
}

