--- / PURPOSE: Different states the game server session can be in. You shouldnt need to use it.
--- /
---@class GAMESERVER_STATES
GAMESERVER_STATES = {
	GAMESERVER_INVALID = 0,
	GAMESERVER_PENDING_ACCESS_TOKEN = 1,
	WAIT_FOR_START_SESSION = 2,
	PENDING_CATALOG_VERSION = 3,
	GAMESERVER_PENDING_CATALOG = 4,
	GAMESERVER_CATALOG_COMPLETE = 5,
	GAMESERVER_PENDING_SESSION_START = 6,
	GAMESERVER_PENDING_SESSION_RESTART = 7,
	GAMESERVER_READY = 8,
	GAMESERVER_FAILED_ACCESS_TOKEN = 9,
	GAMESERVER_FAILED_CATALOG = 10,
	GAMESERVER_FAILED_SESSION_START = 11,
	GAMESERVER_FAILED_SESSION_RESTART = 12,
}

--- Possible error codes for transactions
---@class GAMESERVERRESULTS
GAMESERVERRESULTS = {
	GAMESERVER_SUCCESS = 0,
	GAMESERVER_ERROR_UNDEFINED = 1,
	GAMESERVER_ERROR_NOT_IMPLEMENTED = 2,
	GAMESERVER_ERROR_SYSTEM_ERROR = 3,
	GAMESERVER_ERROR_INVALID_DATA = 4,
	GAMESERVER_ERROR_INVALID_PRICE = 5,
	GAMESERVER_ERROR_INSUFFICIENT_FUNDS = 6,
	GAMESERVER_ERROR_INSUFFICIENT_INVENTORY = 7,
	GAMESERVER_ERROR_INCORRECT_FUNDS = 8,
	GAMESERVER_ERROR_INVALID_ITEM = 9,
	GAMESERVER_ERROR_INVALID_PERMISSIONS = 10,
	GAMESERVER_ERROR_INVALID_CATALOG_VERSION = 11,
	GAMESERVER_ERROR_INVALID_TOKEN = 12,
	GAMESERVER_ERROR_INVALID_REQUEST = 13,
	GAMESERVER_ERROR_INVALID_ACCOUNT = 14,
	GAMESERVER_ERROR_INVALID_NONCE = 15,
	GAMESERVER_ERROR_EXPIRED_TOKEN = 16,
	GAMESERVER_ERROR_CACHE_OPERATION = 17,
	GAMESERVER_ERROR_INVALID_LIMITER_DEFINITION = 18,
	GAMESERVER_ERROR_GAME_TRANSACTION_EXCEPTION = 19,
	GAMESERVER_ERROR_EXCEED_LIMIT = 20,
	GAMESERVER_ERROR_EXCEED_LIMIT_MESSAGE = 21,
	GAMESERVER_ERROR_AUTH_FAILED = 22,
	GAMESERVER_ERROR_STALE_DATA = 23,
	GAMESERVER_ERROR_BAD_SIGNATURE = 24,
	GAMESERVER_ERROR_INVALID_CONFIGURATION = 25,
	GAMESERVER_ERROR_NET_MAINTENANCE = 26,
	GAMESERVER_ERROR_USER_FORCE_BAIL = 27,
	GAMESERVER_ERROR_CLIENT_FORCE_FAILED = 28,
	GAMESERVER_ERROR_INVALID_GAME_VERSION = 29,
}

--- Possible network shot transaction status.
---@class NET_GAMESERVER_TRANSACTION_STATUS
NET_GAMESERVER_TRANSACTION_STATUS = {
	TRANSACTION_STATUS_NONE = 0,
	TRANSACTION_STATUS_PENDING = 1,
	TRANSACTION_STATUS_FAILED = 2,
	TRANSACTION_STATUS_SUCCESSFULL = 3,
	TRANSACTION_STATUS_CANCELED = 4,
}

--- Defines for the flags that can be set when adding items to the basket or adding services.
---@class CATALOG_ITEM_FLAGS
CATALOG_ITEM_FLAGS = {
	CATALOG_ITEM_FLAG_WALLET_ONLY = 1,
	CATALOG_ITEM_FLAG_BANK_ONLY = 2,
	CATALOG_ITEM_FLAG_BANK_THEN_WALLET = 4,
	CATALOG_ITEM_FLAG_WALLET_THEN_BANK = 8,
	CATALOG_ITEM_FLAG_EVC_ONLY = 16,
	CATALOG_ITEM_FLAG_TOKEN = 32,
}

--- Defines for item storage types.
---@class SHOP_ITEM_STORAGE
SHOP_ITEM_STORAGE = {
	NET_SHOP_ISTORAGE_INT = 0,
	NET_SHOP_ISTORAGE_INT64 = 1,
	NET_SHOP_ISTORAGE_BITFIELD = 2,
}

