---@class eEMAIL_RETRIEVAL_STATUS
eEMAIL_RETRIEVAL_STATUS = {
	EMAIL_RETRIEVAL_NONE = 0,
	EMAIL_RETRIEVAL_PENDING = 1,
	EMAIL_RETRIEVAL_FAILED = 2,
	EMAIL_RETRIEVAL_SUCCEEDED = 3,
	EMAIL_RETRIEVAL_CANCELLED = 4,
}

---@class ePROFANITY_CHECK_STATUS
ePROFANITY_CHECK_STATUS = {
	PROFANITY_RESULT_OK = 0,
	PROFANITY_RESULT_FAILED = 1,
	PROFANITY_RESULT_PENDING = 2,
	PROFANITY_RESULT_INVALID_TOKEN = 3,
	PROFANITY_RESULT_ERROR = -1,
}

---@class eLICENSEPLATE_CHECK_STATUS
eLICENSEPLATE_CHECK_STATUS = {
	LICENSEPLATE_RESULT_OK = 0,
	LICENSEPLATE_RESULT_FAILED = 1,
	LICENSEPLATE_RESULT_PENDING = 2,
	LICENSEPLATE_RESULT_INVALID_TOKEN = 3,
	LICENSEPLATE_RESULT_ERROR = -1,
}

---@class eLICENSEPLATE_ADD_STATUS
eLICENSEPLATE_ADD_STATUS = {
	LICENSEPLATE_ADD_OK = 0,
	LICENSEPLATE_ADD_PENDING = 1,
	LICENSEPLATE_ADD_INVALID_TOKEN = 2,
	LICENSEPLATE_ADD_ERROR = -1,
}

--- Bit fields used to specify the plate data.
---@class ePlateDataValuesBits
ePlateDataValuesBits = {
	PLATE_DATA_GIFTED_PLATE = 1, -- == �NoDelete� string
	PLATE_DATA_SPPLATE = 2, -- == �SPPlate� string
}

---@class eLICENSEPLATE_CHANGE_STATUS
eLICENSEPLATE_CHANGE_STATUS = {
	LICENSEPLATE_CHANGE_RESULT_OK = 0,
	LICENSEPLATE_CHANGE_RESULT_PENDING = 1,
	LICENSEPLATE_CHANGE_RESULT_ERROR = -1,
}

---@class eLICENSEPLATE_ISVALID_STATUS
eLICENSEPLATE_ISVALID_STATUS = {
	LICENSEPLATE_ISVALID_OK = 0,
	LICENSEPLATE_ISVALID_PENDING = 1,
	LICENSEPLATE_ISVALID_PROFANE = 2,
	LICENSEPLATE_ISVALID_RESERVED = 3,
	LICENSEPLATE_ISVALID_MALFORMED = 4,
	LICENSEPLATE_ISVALID_NOTVALID = 5,
	LICENSEPLATE_ISVALID_INVALID_TOKEN = 6,
	LICENSEPLATE_ISVALID_ERROR = -1,
}

