--- Corresponds to LandingPageConfig::eEntryPoint
---@class LANDING_PAGE_ENTRYPOINT
LANDING_PAGE_ENTRYPOINT = {
	ENTRYPOINT_MODE_SELECT = 1,
	ENTRYPOINT_SINGLEPLAYER_MIGRATION = 2,
	ENTRYPOINT_MULTIPLAYER_REVIEW_CHARACTERS = 3,
	ENTRYPOINT_MULTIPLAYER_MIGRATE_CHARACTER = 4,
	ENTRYPOINT_STORYMODE_UPSELL = 7,
	ENTRYPOINT_WINDFALL = 8,
	ENTRYPOINT_COUNT = 12,
}

