---@class CHANNEL_SEVERITY
CHANNEL_SEVERITY = {
	CHANNEL_SEVERITY_FATAL = 0,
	CHANNEL_SEVERITY_ASSERT = 1,
	CHANNEL_SEVERITY_ERROR = 2,
	CHANNEL_SEVERITY_WARNING = 3,
	CHANNEL_SEVERITY_DISPLAY = 4,
	CHANNEL_SEVERITY_DEBUG1 = 5,
	CHANNEL_SEVERITY_DEBUG2 = 6,
	CHANNEL_SEVERITY_DEBUG3 = 7,
}

---@class CHANNEL_TYPE
CHANNEL_TYPE = {
	CHANNEL_FILELOG_LEVEL = 0,
	CHANNEL_TTY_LEVEL = 1,
	CHANNEL_POPUP_LEVEL = 2,
}

