--- script_hud_enums.sch
--- all standard scaleform scripthud components
--- 
--- eHUD_COMPONENT - list of all CODE hud components
--- 
---@class eHUD_COMPONENT
eHUD_COMPONENT = {
	NEW_HUD_WANTED_STARS = 1,
	NEW_HUD_WEAPON_ICON = 2,
	NEW_HUD_CASH = 3,
	NEW_HUD_MP_CASH = 4,
	NEW_HUD_MP_MESSAGE = 5,
	NEW_HUD_VEHICLE_NAME = 6,
	NEW_HUD_AREA_NAME = 7,
	NEW_HUD_DISTRICT_NAME = 8,
	NEW_HUD_STREET_NAME = 9,
	NEW_HUD_HELP_TEXT = 10,
	NEW_HUD_FLOATING_HELP_TEXT_1 = 11,
	NEW_HUD_FLOATING_HELP_TEXT_2 = 12,
	NEW_HUD_CASH_CHANGE = 13, -- used to be NEW_HUD_FLOATING_HELP_TEXT_3
	NEW_HUD_RETICLE = 14,
	NEW_HUD_SUBTITLE_TEXT = 15,
	NEW_HUD_RADIO_STATIONS = 16,
	NEW_HUD_SAVING_GAME = 17,
	NEW_HUD_FEED = 18,
	NEW_HUD_WEAPON_WHEEL = 19,
	NEW_HUD_WEAPON_WHEEL_STATS = 20,
}

--- 
--- eSCRIPT_HUD_COMPONENT - list of all SCRIPT hud components
--- 
---@class eSCRIPT_HUD_COMPONENT
eSCRIPT_HUD_COMPONENT = {
	HUD_DRUGS_PURSE_01 = 0,
	HUD_DRUGS_PURSE_02 = 1,
	HUD_DRUGS_PURSE_03 = 2,
	HUD_DRUGS_PURSE_04 = 3,
	HUD_MP_TAG_CASH_FROM_BANK = 4,
	HUD_MP_TAG_PACKAGES = 5,
	HUD_MP_TAG_CUFF_KEYS = 6,
	HUD_MP_TAG_DOWNLOAD_DATA = 7,
	HUD_MP_TAG_IF_PED_FOLLOWING = 8,
	HUD_MP_TAG_KEY_CARD = 9,
	HUD_MP_TAG_RANDOM_OBJECT = 10,
	HUD_MP_TAG_REMOTE_CONTROL = 11,
	HUD_MP_TAG_CASH_FROM_SAFE = 12,
	HUD_MP_TAG_WEAPONS_PACKAGE = 13,
	HUD_MP_TAG_KEYS = 14,
	HUD_MP_VEHICLE = 15,
	HUD_MP_VEHICLE_HELI = 16,
	HUD_MP_VEHICLE_PLANE = 17,
	HUD_PLAYER_SWITCH_ALERT = 18,
	HUD_MP_RANK_BAR = 19,
	HUD_DIRECTOR_MODE = 20,
	HUD_CHIP = 21, -- Casino chips display
	HUD_CHIP_CHANGE = 22, -- Casino chips value change
	HUD_MP_TAG_LARGE_PACKAGES = 23, -- Not listed in the code side enum
	HUD_MP_TAG_GANG_CEO = 24, -- Not listed in the code side enum
	HUD_MP_TAG_GANG_BIKER = 25, -- Not listed in the code side enum
}

--- 
--- BRIEF_TYPE - types of brief string - for use with ADD_TEXT_COMPONENT_SUBSTRING_LATEST_BRIEF_STRING and SCALEFORM_MOVIE_METHOD_ADD_PARAM_LATEST_BRIEF_STRING
--- 
---@class BRIEF_TYPE
BRIEF_TYPE = {
	PREV_MESSAGE_TYPE_DIALOG = 0,
	PREV_MESSAGE_TYPE_HELP = 1,
	PREV_MESSAGE_TYPE_MISSION = 2,
}

