---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 28/12/2023 13:48
---

EULER_XYZ = 0
EULER_XZY = 1
EULER_YXZ = 2
EULER_YZX = 3
EULER_ZXY = 4
EULER_ZYX = 5
EULER_MAX = 6